### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [hectorm/hblock#100]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/smashah/smashblock/master/blocklist.txt). Thanks!

**Comment by hectorm** [comment]
Hi, I have searched on the list and found no evidence. The link you provide does not belong to this project.

**Comment by BitCannaGlobal** [comment]
Good day

I see indeed. Our since apologies for the inconvenience!

With kind regards
The BitCanna team
