### ISSUE TITLE
Add date when hosts file was last updated

### ISSUE THREAD

**Issue by therealthingy** [hectorm/hblock#103]
Currently, `hblock` lists version information and the # of blocked domains:
```
> head -10 /etc/hosts
# Generated with hBlock 3.3.2 (https://github.com/hectorm/hblock)
# Blocked domains: 235517

# BEGIN HEADER
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
```

However, it would be nice to have additionally a **date, when the list was last updated**, e.g.:
`# Generated on Fri Jun 24 12:42:07 CEST 2022`

**Comment by hectorm** [comment]
I have just released a new version with this implemented.
