### ISSUE TITLE
Hblock not working when installed via Linux for Windows subsystem

### ISSUE THREAD

**Issue by LostAccount** [hectorm/hblock#105]
**Describe the bug:**
Doesn't seem to work if installed in the Linux subsystem for Windows 10. (EDIT - I suspect that this might be expected behavior due the linux implementation being layered in Windows)

**Steps to reproduce:**
install hblock via brew and visit https://hblock.molinero.dev/. Site reports "You are not using hBlock"

**Expected behavior:**
Hblock blocks domains

**Environment:**
 - OS: Linux subsystem for Windows 10

**Comment by hectorm** [comment]
If you run hBlock inside the WSL VM the entries added to the hosts file will only work inside that VM, it is the expected behavior.
