### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by Gummibando** [hectorm/hblock#108]
Not sure if this fits the issue category as it is more of a general question (but it might result in a feature request).

Is it possible to block IPv6 in addition to IPv4?
I.e., in addition to 0.0.0.0, map domains to **::** (or **::**/0 ?).

As far as I can see, I can only do either one **or** the other via the -R option.

Best, Oli

**Comment by hectorm** [comment]
It is possible to generate a hosts file with both IPv4 and IPv6 entries but I don't quite understand the point of this, why do you need to have both entries? In principle with either of them in the hosts file you should block access to the domain.

To do this you can ignore the `-R` option and directly use the following template with the `-T` option.
```sh
hblock -T '0.0.0.0 %D\n:: %D' -O ./hosts
```

**Comment by Gummibando** [comment]
Hi Hector,
sorry, I forgot to mention that this is macOS-specific.

I'm really far from an expert in this, but according to https://macnative.com/why-is-macos-ignoring-hosts-file-entries/ macOS prefers IPv6 over IPv4, including DNS queries, when configured accordingly. This is what I experienced ("normal" ping to a blocked domain: Socket not connected, ping6: host resolved and responding) after I had set up IPv6 support in my local environment (client devices/router etc.).

Thank you very much for the template. While I know that this is really not optimal as it basically doubles the file size, this makes the "blocking" work again with IPv6 enabled.

Best, Oli

**Comment by hectorm** [comment]
I'm glad this solved your use case. Also thanks for your sponsorship on GitHub!

**Comment by Gummibando** [comment]
Slight correction (saw #113 just by chance, will comment there as well):

For macOS, the command needs to be

hblock -T '0.0.0.0 %D\n:: %D' -O

otherwise the hosts file is created in the root of the macOS user home folder.
By omitting to explicitly set the  output file `./hosts`, the default macOS path for the hosts file `/etc/hosts` is used.
