### ISSUE TITLE
I need a way to add/control the number attemps when downloading a source.

### ISSUE THREAD

**Issue by tuqueque** [hectorm/hblock#109]
Hello, first of all, thank you for this awesome tool! I've been using it for a couple of years now and it works amazingly!

But there's a problem that over time has become unbearable, and is that over the years I have built a massive list of host sources (187 sources so far) and sometimes one... or a few of those sources becomes temporarily unavailable or more commonly, their connection becomes slow or intermittent; which constantly makes hblock close with an error and I have to run it again, and again... and again until either succeeds or I give up after an hour wanting to throw the computer out the window!

Is there a way of making hblock automatically repeat several times (with a parameter controlled by the user) before giving up and instead of just exit with an error, just move to the next source in the list?

I REALLY hope this is possible to implement, 'cause this is becoming unbearable as I make my sources list more extensive.

Thanks in advance!

**Comment by hectorm** [comment]
With the `-c` (`--continue`) option you can ignore download errors, but currently there is no retry or timeout option implemented.

I think it's a good idea to offer more control over downloads, as long as `curl`, `wget` and `fetch` support the feature it's not hard to add one more option.

In the meantime you can manually modify the [`fetchUrl`](https://github.com/hectorm/hblock/blob/v3.4.0/hblock#L318-L331) function to suit your needs.
