### ISSUE TITLE
unbound.conf.sh does not match hosts

### ISSUE THREAD

**Issue by nimbius** [hectorm/hblock#110]
**Describe the bug:**
unbound.conf has 50% fewer lines than the hosts file it is generated from

**Steps to reproduce:**
generate unbound zone using the resource script provided.

**Expected behavior:**
hosts and unbound zone should be 1:1

**Environment:**
 - OS: I use arch BTW
 - Other details that you think may affect.

**Additional context:**

**Comment by hectorm** [comment]
The Unbound configuration file has fewer domains because it is being generated with the `--filter-subdomains` option to filter out all subdomains of domains that are already blocked. This is because Unbound should already by default block any subdomains.
