### ISSUE TITLE
dnsmasq should map domain to 0.0.0.0

### ISSUE THREAD

**Issue by bokunodev** [hectorm/hblock#114]
**Is your feature request related to a problem? Please describe:**

Android chrome browser will retry with different dns provider (_google_), if dns server from the network response with NXDOMAIN, make dns based adblock **uneffective**.

**Describe the solution you'd like:**

`address=/example.com/0.0.0.0`
instead of 
`address=/example.com/`

**Describe alternatives you've considered:**

My current solution is by appending `0.0.0.0` to each line, manually using `sed`

**Additional context:**
Add any other context about the feature request here.

I didn't use [`hblock` ](https://github.com/hectorm/hblock/blob/master/hblock) to manage blocklist.

**Comment by hectorm** [comment]
It is not sustainable to provide pre-built configuration files that satisfy all use cases, fortunately hBlock is quite flexible and in your specific scenario the following command would generate the dnsmasq configuration you are looking for:

```sh
hblock -T 'address=/%D/%R' -R '127.0.0.1' -O ./hblock_dnsmasq.conf
```
