### ISSUE TITLE
Help for add deny or white url

### ISSUE THREAD

**Issue by mmlg620** [hectorm/hblock#115]
Hello,

Your software is what I was looking for and it works perfectly. I'm very pleased with it.
I would like to add sites to the blacklist and also to the white list.
I have read the help >> "hblock --help" but I don't understand the command syntax and how to do it.
Is it possible to have 2 concrete cases of entry (white list, black list) with this url taken as an example:

https://easylist.to/easylist/easylist.txt

Thanks in advance

**Comment by hectorm** [comment]
Sorry for my late reply, I was on a trip this week.

You can add domains to a whitelist file and specify their location with the `--allowlist` option, the same for a blacklist but using the `--denylist` option.

```sh
hblock --allowlist /tmp/allow.list --denylist /tmp/deny.list
```

The default values for these options are `/etc/hblock/allow.list` and `/etc/hblock/deny.list`, so you can also create these files and hBlock will use them automatically without having to specify these options.

The content of these files is a list of domains separated by new lines.

I don't quite understand the example you are asking for with that URL.
