### ISSUE TITLE
How do you remove HBLOCK

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [hectorm/hblock#118]
I get too much false positive, how to remove it safely ?

**Comment by hectorm** [comment]
Depends on how you installed it. If it was through a package manager use the appropriate command to uninstall packages, if you simply downloaded the script just deleting it and restoring your hosts file is enough.

**Comment by hectorm** [comment]
I'm closing this, if you have any doubt feel free to reopen it.

**Comment by jojojojojoj5564656465465** [comment]
Could you tell me what to do next because the site keep be blocked
`cd Documents
hblock -A mylist.txt
`

What do i need to do next?

`[INFO] Applying allowlist
[INFO] 298995 blocked domains!`  <- the Number is still the same 

Also hblock didn't create an allow.list in the /etc/hblock so i did myselft. I tried to add [dealabs.digidip.net](dealabs.digidip.net) but

**Comment by hectorm** [comment]
I don't quite understand what you want to achieve, I assumed you wanted to uninstall hBlock completely from the system.

Do you want to add a domain to the allow list instead?

**Comment by jojojojojoj5564656465465** [comment]
![Peek 18-01-2023 23-28](https://user-images.githubusercontent.com/45184918/213309712-cb4a2f5a-6975-4b40-b365-206337f7cd69.gif)

For exemple here it doesn't block anything. It also reset everything when i do hblock ?

**Comment by hectorm** [comment]
From what I can see in the gif, you are specifying several domains in the `deny.txt` file and it looks like they are being added to the hosts file correctly. But I don't know if your intention is to allow or deny access to these domains.

Is it possible that the problem you are having is that your browser is able to access these domains even though they are being blocked?

Could you give me the output of these three commands?

```sh
head -30 /etc/hosts
```

```sh
tail -30 /etc/hosts
```

```sh
grep -C2 '[[:blank:]]lemonde\.fr$' /etc/hosts
```

Every time you run the `hblock` command the `/etc/hosts` file of your system is updated.

**Comment by jojojojojoj5564656465465** [comment]
`# Generated with hBlock 3.4.0 (https://github.com/hectorm/hblock)
# Blocked domains: 299595
# Date: Wed Jan 18 23:47:45 CET 2023

# BEGIN HEADER
127.0.0.1       localhost manjaro-systemproductname
255.255.255.255 broadcasthost
::1             localhost manjaro-systemproductname
::1             ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
ff02::3         ip6-allhosts
# END HEADER

# BEGIN BLOCKLIST
0.0.0.0 -043ns11.net.daraz.com
0.0.0.0 -16marketing.net.daraz.com
0.0.0.0 -access-logs-active.net.daraz.com
0.0.0.0 -access-logsacc-sandbox.net.daraz.com
0.0.0.0 -access-logsactive.net.daraz.com
0.0.0.0 -azure-freya.net.daraz.com
0.0.0.0 -car2101-echo-tls.net.daraz.com
0.0.0.0 -car213apropmdeizy9vjf.net.daraz.com
0.0.0.0 -chef.net.daraz.com
0.0.0.0 -client.net.daraz.com
0.0.0.0 -cloudapp-car10.net.daraz.com
0.0.0.0 -demo.net.daraz.com
0.0.0.0 -production10537981.net.daraz.com`

`    ~  tail -30 /etc/hosts                                                    ✔
0.0.0.0 zzim.000webhostapp.com
0.0.0.0 zzjwcn.wixsite.com
0.0.0.0 zzkadra-kwbbelchatow.com.pl
0.0.0.0 zzkj.biz
0.0.0.0 zzkwg.comfortykive.xyz
0.0.0.0 zzltuq.webwave.dev
0.0.0.0 zzmalwo.pl
0.0.0.0 zzmmkj.com
0.0.0.0 zzngisyq.xyz
0.0.0.0 zzoluickymwz.com
0.0.0.0 zzpwwbf.cn
0.0.0.0 zzpzero.com
0.0.0.0 zzqqhb.com
0.0.0.0 zzsno1.com
0.0.0.0 zzsqqx.shopjapan.co.jp
0.0.0.0 zzwzsic.cn
0.0.0.0 zzx.chainreact.xyz
0.0.0.0 zzx.gaznf.xyz
0.0.0.0 zzxedr.xyz
0.0.0.0 zzxhx.com
0.0.0.0 zzxjlr.com
0.0.0.0 zzxxli.club
0.0.0.0 zzycj.com
0.0.0.0 zzyl.mobi
0.0.0.0 zzyytt.top
0.0.0.0 zzz.onion.pet
0.0.0.0 zzzhuoxiaqu.online
0.0.0.0 zzznews.ru
0.0.0.0 zzzyyzzzyyyzyyzyyyzzyyzyzzzzzzzzyyzzyyyyyzyzyyzzyzpol7196.cmkaarten.nl
# END BLOCKLIST`

`grep -C2 '[[:blank:]]lemonde\.fr$' /etc/hosts`  NOTHING RETURNED

**Comment by jojojojojoj5564656465465** [comment]
Is it normal that  it doesn't generate an allow.list and a deny.list in /etc/hblok ?

![image](https://user-images.githubusercontent.com/45184918/213330307-3d7c2c87-e631-4556-92c0-cf22e6824a1e.png)

**Comment by jojojojojoj5564656465465** [comment]
[https://fromsmash.com/hblock](video)

When i put hblock it delete all my lists

**Comment by jojojojojoj5564656465465** [comment]
Do you think you could do a prompt with this tool to make flags easier to memorize ? [](https://github.com/charmbracelet/gum)
