### ISSUE TITLE
Sources List Not Download 

### ISSUE THREAD

**Issue by velan001** [hectorm/hblock#119]
If I run run block . It will stop in some lines not complete the sources downloading. 
![IMG_20230131_073003.jpg](https://user-images.githubusercontent.com/124013073/215644788-eb56a1de-3588-4bbb-8227-936f8a2758e1.jpg)

**Comment by hectorm** [comment]
hBlock simply uses curl, wget or fetch to download the sources. There seems to be some kind of network problem in your environment.

If you try to get a source directly with curl, does it work?
```sh
curl -vI https://raw.githubusercontent.com/hectorm/hmirror/master/data/adaway.org/list.txt
```

**Comment by velan001** [comment]
> hBlock simply uses curl, wget or fetch to download the sources. There seems to be some kind of network problem in your environment.
> 
> If you try to get a source directly with curl, does it work?
> ```sh
> curl -vI https://raw.githubusercontent.com/hectorm/hmirror/master/data/adaway.org/list.txt
> ```

I am from India if i will use VPN the sources will be download. It is the problem where the country I can use make the issue ?

**Comment by hectorm** [comment]
I remember reading recently that GitHub has been partially blocked in India, it is possible that this is the cause.
https://news.ycombinator.com/item?id=34231553

I suggest that you replace all the sources in hBlock with one of the mirrors I offer.
https://github.com/hectorm/hblock/blob/master/SOURCES.md

For example, try replacing all references to `https://raw.githubusercontent.com/hectorm/hmirror/master/data/` with `https://hmirror.molinero.dev/`.

**Comment by velan001** [comment]
> I remember reading recently that GitHub has been partially blocked in India, it is possible that this is the cause.
> https://news.ycombinator.com/item?id=34231553
> 
> I suggest that you replace all the sources in hBlock with one of the mirrors I offer.
> https://github.com/hectorm/hblock/blob/master/SOURCES.md
> 
> For example, try replacing all references to `https://raw.githubusercontent.com/hectorm/hmirror/master/data/` with `https://hmirror.molinero.dev/`.

Ok bro I will Try it

**Comment by velan001** [comment]
> > I remember reading recently that GitHub has been partially blocked in India, it is possible that this is the cause.
> > https://news.ycombinator.com/item?id=34231553
> > 
> > I suggest that you replace all the sources in hBlock with one of the mirrors I offer.
> > https://github.com/hectorm/hblock/blob/master/SOURCES.md
> > 
> > For example, try replacing all references to `https://raw.githubusercontent.com/hectorm/hmirror/master/data/` with `https://hmirror.molinero.dev/`.
> 
> Ok bro I will Try it

Where is the hblock source file present . allow list and deny list only present in etc/hblock folder

**Comment by velan001** [comment]
> > I remember reading recently that GitHub has been partially blocked in India, it is possible that this is the cause.
> > https://news.ycombinator.com/item?id=34231553
> > 
> > I suggest that you replace all the sources in hBlock with one of the mirrors I offer.
> > https://github.com/hectorm/hblock/blob/master/SOURCES.md
> > 
> > For example, try replacing all references to `https://raw.githubusercontent.com/hectorm/hmirror/master/data/` with `https://hmirror.molinero.dev/`.
> 
> Ok bro I will Try it

It Works Bro .
