### ISSUE TITLE
Unblock s.youtube.com

### ISSUE THREAD

**Issue by nishaddesilva** [hectorm/hblock#120]
Please unblock s.youtube.com
I think this is blocked only on Steven Black hosts, and this is crippling YouTube watch history.

Screenshot from Steven Black Hosts:

![5AXZqJ](https://user-images.githubusercontent.com/74057395/218747703-0704e316-6bb3-41da-abef-0b4a780d0861.png)

**Comment by hectorm** [comment]
First of all, thank you for taking the time to open this issue.

I agree to keep this domain blocked by default.

It is very complicated to please everyone and block ads and tracking without breaking anything. This is the reason why I do not maintain a public list of allowed domains, but instead have my own personal list according to my needs.

You can always add this domain to your allowed list if you wish.
