### ISSUE TITLE
opernc 

### ISSUE THREAD

**Issue by necrose99** [hectorm/hblock#121]
[hblock.cron.in.txt](https://github.com/hectorm/hblock/files/10833432/hblock.cron.in.txt)

[hblock.rc.in.txt](https://github.com/hectorm/hblock/files/10833441/hblock.rc.in.txt)

**[initify](https://github.com/goose121/initify)**  

anyrate i converted the units over ..

**Comment by hectorm** [comment]
Sorry, but this OpenRC service does not seem to be ok.
