### ISSUE TITLE
playhydrax.com

### ISSUE THREAD

**Issue by gnadgnaoh** [hectorm/hblock#123]
**Please read this first and then remove it from the issue description.**

The blocklist generated by hBlock comes from multiple sources and I don't maintain a public exception list. Please read [the relevant section of the README.md file](https://github.com/hectorm/hblock/blob/master/README.md#i-found-a-false-positive-what-should-i-do) to know how to proceed.

Some website use playhydrax.com to play video

In any case you can open an issue to let me know about this problem or if the blocklist author doesn't agree to remove the domain.

**Comment by hectorm** [comment]
The domain `playhydrax.com` appears in [easylist/listefr](https://github.com/easylist/listefr), one of hBlock's sources.

If you think it is a false positive you should report it there and in case it is removed it will also be automatically removed from hBlock.
