### ISSUE TITLE
us04logfiles.zoom.us

### ISSUE THREAD

**Issue by 3xploiton3** [hectorm/hblock#128]
![image](https://github.com/hectorm/hblock/assets/19517680/01c751cc-d119-4e2c-b524-6f5506d45a02)

![image](https://github.com/hectorm/hblock/assets/19517680/678e18fd-09ee-49d0-820a-c2e70c650a41)

us04logfiles.zoom.us

annoying windows popup notice, any suggestion?

**Comment by hectorm** [comment]
This domain is present in the AdGuard filters, one of the hBlock sources, specifically it was added in this commit: https://github.com/AdguardTeam/AdguardFilters/commit/e3567166163209a46df2a4e86932d74f65fc2921

I recommend that you add this domain to your exception list if necessary and in parallel report this issue to AdGuard. If the domain is removed from their lists, it will be automatically removed from hBlock in the next update.
