### ISSUE TITLE
Whitelist feature

### ISSUE THREAD

**Issue by CHJ85** [hectorm/hblock#130]
Hi there. In some cases, it's beneficial to see ads. Like for instance while shopping for books on Amazon. Sometime I like to browse through related recommendations. Or if I want to support the website that I'm visiting.
I suggest you implement a whitelist feature. I think it should work something like this:
So let's say you have a text file called "whitelist" where you add all the whitelisted domains. Then each time hblock updates the hosts file, hblock will use the "whitelist" file as a reference and comment out those domains from the hosts file.

**Comment by CHJ85** [comment]
You're right. It's already there. My bad. Sorry.

**Comment by hectorm** [comment]
No problem.
