### ISSUE TITLE
Adding Turkish Ad Hosts

### ISSUE THREAD

**Issue by symbuzzer** [hectorm/hblock#131]
Turkish Ad Hosts project is Necessary hosts file to block tracking (and possibly advertising) networks in commonly used mobile applications (and possibly WEB pages) in Turkey...

Its blocking list is officially used by [AdGuard DNS](https://adguard-dns.io/).

- Hosts: https://raw.githubusercontent.com/symbuzzer/Turkish-Ad-Hosts/main/hosts
- Filter: https://raw.githubusercontent.com/symbuzzer/Turkish-Ad-Hosts/main/adguard/filter.txt

**Comment by hectorm** [comment]
The first step is to add the list to hMirror, which I have just done (https://github.com/hectorm/hmirror/commit/f7bee4d0bc603755e91ad221cf897152d713a137).

In the next days I will evaluate to include it by default in hBlock. Thanks for the suggestion!

**Comment by hectorm** [comment]
I have just released a new version with your list included, thanks for your contribution!
