### ISSUE TITLE
Make the Trimble can't login

### ISSUE THREAD

**Issue by tkp206093** [hectorm/hblock#133]
https://id.trimble.com/ui/sign_in.html?state=eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJvYXV0aF9wYXJhbWV0ZXJzIjp7ImNsaWVudF9pZCI6ImM5MTNhOTBjLTRkY2YtNGFmYi1iM2RiLTYzN2JlMzc3NDZiZiIsInJlZGlyZWN0X3VyaSI6Imh0dHBzOi8vbG9naW4uc2tldGNodXAuY29tL2xvZ2luL3RyaW1ibGVpZC9jYWxsYmFjayIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIiwic2NvcGUiOiJvcGVuaWQgc2tldGNodXAtbG9naW4tcHJvZC1WMiIsInN0YXRlIjoiUVhWMGFFdGxlU0JrWVdJNE9EWmlNeTB4TnpFMkxUUXdZakV0WVRoaE55MWxZbUk1TTJReVpUY3daVFlfIn0sImV4dHJhX3BhcmFtZXRlcnMiOnsibGFuZyI6ImVuIn0sImludGVybmFsX3BhcmFtZXRlcnMiOnt9fQ.KkcQ7M_17usZCdj2Ba7niD0xRyN8-a7Zm5PjMyZJQXf0S2EJbqm3h1yKlRDolj3Y1zQZignxqfzQOyx2uCc5yvYVaog-sbTIrYG4r4GMjWym-JtD1UIhpZHSVb5qMjD7_LUHT8IgOIA1DR5vIlujcVEZsCEsn8wO-SiB1PYX53QIS4w6xTtpDw3-PGTe67nerDLlMCckW9t7XY1w-hR6T2VfRGexz6DDfgzRw_y8fAxnrxHGEZC9iDe4XMMICExFJpwEykPLFWcuY9pGbDuB9WIOLk6CBp2PPAnFICVxhmY7UR-M_15buPE9mo2jtz67ZmsXo12XJmEEZ10wUJ6HPQ
<img width="1605" alt="image" src="https://github.com/hectorm/hblock/assets/29872453/b5316235-4611-4b05-8645-2ad1a1af3bb9">

**Comment by hectorm** [comment]
This domain is present in the StevenBlack and Turkish Ad Hosts sources. I have seen that you have already reported this upstream and it has been decided not to remove it, I agree with this decision as this is more of a bug in the website.
