### ISSUE TITLE
tradehq.com

### ISSUE THREAD

**Issue by gyCfjSnO** [hectorm/hblock#135]
Invoices sent from [Tradify](https://www.tradifyhq.com/) are served from the domain `tradehq.com`, however customers are unable to view the invoices as the domain `tradehq.com` is blocked. Removal of this domainfrom your blocklist would allow customers to view invoices sent to them using [Tradify](https://www.tradifyhq.com/).

<img width="1233" alt="tradehq com" src="https://github.com/hectorm/hblock/assets/49738152/6bb7a9e6-fa2f-4fce-adf8-eb9e9d3470f2">

**Comment by drego85** [comment]
Hi, thanks for the report!

At next generation the domain will be removed from the Phishing Army blocklist!
