### ISSUE TITLE
openwrt bug

### ISSUE THREAD

**Issue by timetoseek** [hectorm/hblock#137]
Hblock is using a transfer encoding ("br") which is not supported by uclient-fetch and/or curl (at least by the libcurl lib provided by openwrt, e.g. the parameter "--compressed" is not supported).

Can you please enable deflate encoding too? It seems to be a misconfiguration of server (server must respect encodings from the header sent by HTTP client).

**Comment by hectorm** [comment]
hBlock in the calls to curl, wget or fetch does not specify a specific transfer encoding, it uses the default options of each tool.

Can you give me a curl or wget command that reproduces this problem in OpenWrt?

**Comment by timetoseek** [comment]
Can you also please enable deflate encoding? This seems to be an obvious misconfiguration of the Server, as the Server must respect encodings from the header sent by the HTTP client. Thank you!

**Comment by hectorm** [comment]
Oh, I thought you were referring to the hBlock script and not the website.

It seems I've been bitten by traefik/traefik#9734, expected for a beta version. I've updated the server configuration and it should now work correctly.

**Comment by timetoseek** [comment]
Excellent, confirmed that it is now working. I will now close this issue. Thank you!
