### ISSUE TITLE
Add d3ward/toolz list to the used resources

### ISSUE THREAD

**Issue by mdosch** [hectorm/hblock#140]
Dear hectorm,

I discovered some ad/tracking domains in https://github.com/d3ward/toolz#ad-block-test--link which are not covered by hblock.
Maybe this list could also be added to the hblock resources?

Best regards,
Martin

**Comment by hectorm** [comment]
The d3Host list looks like a nice addition to hBlock. 

<details><summary>These are the domains it currently adds that are not covered by hBlock's default lists:</summary>

```
adm.hotjar.com
ads-api.tiktok.com
adtech.yahooinc.com
advertising.apple.com
advertising.yandex.ru
api.bugsnag.com
api.luckyorange.com
api.mouseflow.com
app.bugsnag.com
app.getsentry.com
appmetrica.yandex.ru
business-api.tiktok.com
careers.hotjar.com
cdn-test.mouseflow.com
ck.ads.oppomobile.com
claritybt.freshmarketer.com
events.hotjar.io
fwtracks.freshmarketer.com
identify.hotjar.com
insights.hotjar.com
log.byteoversea.com
log.fc.yahoo.com
metrika.yandex.ru
realtime.luckyorange.com
surveys.hotjar.com
tools.mouseflow.com
udcm.yahoo.com
udc.yahoo.com
```

</details>

I have created a mirror in the hMirror project for now and will evaluate adding it to hBlock by default. 

Thanks for your contribution!
