### ISSUE TITLE
USOM list add please

### ISSUE THREAD

**Issue by Soickan** [hectorm/hblock#141]
Hi,

Add please Official Turk Cyber Block Center (www.usom.gov.tr) block list.

This list address: https://www.usom.gov.tr/url-list.txt

Thanks

**Comment by hectorm** [comment]
I've created a mirror for this list in [hMirror](https://github.com/hectorm/hmirror/commit/5aa3ebfd90e2e08e9af6bee2ec2b5b2c0fa4a9ad), but I can't guarantee that it will be included in hBlock by default, as over 230k new domains would be added to the list and it's difficult to check for false positives or side effects.

**Comment by Soickan** [comment]
Since this list does not have ad blocking etc., I do not think it will cause any problems as it is included in the list of fake and misleading sites. Since it is an official site, we use it reliably. I'm sure it will give your list a boost. You can learn the details of blocked sites one by one at https://www.usom.gov.tr/adres .

**Comment by hectorm** [comment]
Just to update, I am still considering including it by default, so far I have not encountered any problems with it.
