### ISSUE TITLE
[FEATURE REQUEST] : add flags for blocks extra contents (porn, social networks , etc.)

### ISSUE THREAD

**Issue by thealio** [hectorm/hblock#142]
Hi,
in my opinion , it could be great to have flags for generate an hostfile that block extra content , like porn-websites , social network etc. , as Steve Blake does in his hostfiles ( https://github.com/StevenBlack/hosts )
As example
hblock --porn     --> generate the default hblock host file with extra blocking for porn sites
hblock --social   --> generate the default hblock host file with extra blocking for social networks

with flags that can be combined ( hblock --porn --social )

**Comment by hectorm** [comment]
I'm sorry, but I think classifying sources is outside the scope of this project.
