### ISSUE TITLE
why *.xtracloud.net blocked?

### ISSUE THREAD

**Issue by flexxxxer** [hectorm/hblock#143]

**Comment by hectorm** [comment]
I think these domains should not be blocked from what I read in hagezi/dns-blocklists#1023.

They are currently on the symbuzzer/Turkish-Ad-Hosts list, could you take a look at this @symbuzzer?

**Comment by symbuzzer** [comment]
@hectorm @flexxxxer Sorry for the delay, I was a little unwell. Thank you very much for the report. I will check it immediately, take the necessary action and inform you here.

**Comment by flexxxxer** [comment]
I agree, it makes sense
