### ISSUE TITLE
No polish easy list in sources

### ISSUE THREAD

**Issue by bardbit** [hectorm/hblock#145]
Hello, great job, but from what I noticed in the sources there is no Polish version of easylist. In my country, unfortunately, most ads are not blocked. Is it possible to add new source? Can I do it myself? I didn't find any instructions. Regards and once again, great job

link if you need it: https://github.com/easylistpolish/easylistpolish

**Comment by hectorm** [comment]
I have added the list to hBlock, although after processing it to convert it to a format suitable for a hosts file, it is not of much value as it only contains 3 domains.
