### ISSUE TITLE
Block OneTrust Privacy Annoyances

### ISSUE THREAD

**Issue by riei2922jww** [hectorm/hblock#149]
Please add:
my.onetrust.com
geolocation.onetrust.com
mobile-data.onetrust.io

To the blocklist to prevent these annoying cookie pop-ups on 70% of mobile-based applications.
![image](https://github.com/hectorm/hblock/assets/154846714/fd320536-fe0b-499b-8d03-39c1ece565bc)

**Comment by hectorm** [comment]
I do not personally maintain a blocklist, hBlock is powered by several third party sources. If you want a domain to be blocked by default, you should submit it to [one of these sources](https://github.com/hectorm/hblock/blob/master/SOURCES.md) and it will be automatically blocked by hBlock in the next update.
