### ISSUE TITLE
mail.cock.li, a legitimate free email service get's block by hBlock

### ISSUE THREAD

**Issue by Uneccessary** [hectorm/hblock#150]
**Please read this first and then remove it from the issue description.**

The blocklist generated by hBlock comes from multiple sources and I don't maintain a public exception list. Please read [the relevant section of the README.md file](https://github.com/hectorm/hblock/blob/master/README.md#i-found-a-false-positive-what-should-i-do) to know how to proceed.

In any case you can open an issue to let me know about this problem or if the blocklist author doesn't agree to remove the domain.

- I will try to find the list which causes this

**Comment by hectorm** [comment]
Thanks for the report, I removed the USOM list because it had too many dead domains and also this domain, so the issue is fixed.
