### ISSUE TITLE
MarineTraffic

### ISSUE THREAD

**Issue by AnimMouse** [hectorm/hblock#152]
It is a ship tracking website.
https://marinetraffic.com

**Comment by hectorm** [comment]
It's been blocked by Matomo (matomo-org/referrer-spam-list#1070) for a while, could you check it @spmedia?

**Comment by AnimMouse** [comment]
I think you should not include that list on this blocklist, since "referrer spam" (assuming that MarineTraffic is truly performing referrer spamming) is [aimed at search engines](https://en.wikipedia.org/wiki/Referrer_spam), not to end users like us.

**Comment by hectorm** [comment]
I'm aware of the concept, but usually the sites that engage in this practice are also undesirable to the end user. I still think MarineTraffic is a false positive, let's wait and see if the list maintainer can check it.

**Comment by spmedia** [comment]
It was indeed a false positive.

MarineTraffic.com has been removed (in #1387)

Thanks for letting us know!
