### ISSUE TITLE
d.mlcdn.com.br

### ISSUE THREAD

**Issue by fabianski7** [hectorm/hblock#154]
This domain seems to be used for fingerprinting, but it's important for magazineluiza.com.br because blocking it breaks the login.

I've already reported it to the block list where it is, I don't think they'll remove the domain. Apparently it's best to leave this task to the browser's ad blocker.
https://github.com/AdguardTeam/cname-trackers/issues/94

![image](https://github.com/hectorm/hblock/assets/47755037/c54ed46e-59eb-4c1f-a1ac-785e1318b14d)

![image](https://github.com/hectorm/hblock/assets/47755037/98102da1-0a08-4425-88d7-1f205816a4c6)

**Comment by hectorm** [comment]
Sorry for the late reply, I removed the AdGuard - CNAME trackers list for the reason mentioned in https://github.com/AdguardTeam/cname-trackers/issues/94#issuecomment-2018329773.
