### ISSUE TITLE
Euronews - blocked videos?

### ISSUE THREAD

**Issue by OrionRandD** [hectorm/hblock#155]
It seems that Euronews is blocked playing videos since I installed it...
https://www.euronews.com/
Before installing hblock, playing videos on the site worked ok.
How can I check this?
Can someone reproduce this behaviour?
Thx

**Comment by hectorm** [comment]
@symbuzzer it seems that blocking `sdk.privacy-center.org` causes videos not to play on some websites ([easylist/easylist#6049](https://github.com/easylist/easylist/issues/6049), [uBlockOrigin/uAssets#7644](https://github.com/uBlockOrigin/uAssets/issues/7644#issuecomment-685268197)), could you evaluate whether or not it is worth having this domain on your block list?

**Comment by symbuzzer** [comment]
> @symbuzzer it seems that blocking `sdk.privacy-center.org` causes videos not to play on some websites ([easylist/easylist#6049](https://github.com/easylist/easylist/issues/6049), [uBlockOrigin/uAssets#7644](https://github.com/uBlockOrigin/uAssets/issues/7644#issuecomment-685268197)), could you evaluate whether or not it is worth having this domain on your block list?

Removing sir, thanks for feedback

**Comment by hectorm** [comment]
Thanks!
