### ISSUE TITLE
afrinic.net

### ISSUE THREAD

**Issue by iSaluki** [hectorm/hblock#156]
The `afrinic.net` domain is a major RIR and should not be blocked. Blocking it impairs access to internet registry services.

**Comment by hectorm** [comment]
Looks like it's being blocked by Phishing Army, could you take a look @drego85?

**Comment by drego85** [comment]
Hi, 
the problem arises from this report: https://www.phishtank.com/phish_detail.php?phish_id=8070577

Obviously it is false positive! :(

I reported the error to Phishtank and whilitested the domain.

Thanks for the report!
