### ISSUE TITLE
vlscppe.microsoft.com

### ISSUE THREAD

**Issue by mikropsoft** [hectorm/hblock#157]
Domain: vlscppe.microsoft.com

Description: This domain belongs to Microsoft's Volume Licensing Service Center (VLSC) portal. The VLSC is a platform used by Microsoft's enterprise customers to manage their software licenses. Through this portal, users can download software, manage licenses, activate new licenses, and generate usage reports.

Note: Downloading any ISO via Rufus results in an error.

**Comment by hectorm** [comment]
Fixed, related to https://github.com/hectorm/hblock/issues/154#issuecomment-2138370587. Thanks!

**Comment by mikropsoft** [comment]
> Fixed, related to https://github.com/hectorm/hblock/issues/154#issuecomment-2138370587. Thanks!

@hectorm I realized there was a problem again.

I use Adguard home, and I noticed this in the logs yesterday.

![Screenshot_2024-06-13-11-14-01-87_47b139e01e88b959d11c5a6697f46196~2.jpg](https://github.com/hectorm/hblock/assets/75412448/74b48233-34a4-4612-a9d0-46c7259b6078)

![Screenshot_2024-06-13-11-14-05-10_47b139e01e88b959d11c5a6697f46196~2.jpg](https://github.com/hectorm/hblock/assets/75412448/49a14354-fbba-4a1b-a477-89a0dc1294dc)

When I go into the details, I see that the vlscppe address is blocked because of another domain.
