### ISSUE TITLE
Google Play App Updates Blocked

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [hectorm/hblock#158]
I am (was) using hBlock as part of several blocklist subscriptions through NextDNS. When I tried to update my apps on the Play Store, nothing was working. I disabled my Private DNS and that fixed the problem, so then I went into NextDNS logs and found that hBlock is blocking many sites on the gvt1.com domain. I removed hBlock from my NextDNS settings and re-enabled Private DNS, then the Google Play updates worked again. Screenshot included of my NextDNS logs.
![Screenshot_20240604-223818](https://github.com/hectorm/hblock/assets/138303650/b0d6f293-f527-44f9-a439-2c5e7735ce0e)

**Comment by shahzebgit** [comment]
Can confirm this, disabled hBlock from block list in nextDNS allowed me to update my play store apps.

**Comment by AyanokojiK1yotaka** [comment]
This is Real i was facing the Same thing. Can't Update my apps in Google playstore.

ALLOW -  ||gvt1.com^

**Comment by carrotice** [comment]
I just added the two web links below as exceptions (in Allowlist) and the Google Play update was enabled again.
```
rr1---sn-uxax3vhna-aw0s.gvt1.com
rr2---sn-uxax3vhna-aw0s.gvt1.com
```

**Comment by gothic-bum** [comment]
Hello Hector,
  
I'm a member of the uBlock Origin team and just wanted to inform you that a fix has been made for this issue. You can refer to the following comment for information regarding the issue:
  
https://old.reddit.com/r/uBlockOrigin/comments/1d8wqdn/why_is_the_gvt1com_domain_blocked/l7arr37/

Best regards, and thanks for the report.

**Comment by hectorm** [comment]
Thank you all, problem solved!
