### ISSUE TITLE
[Add Source]Can you add AWAvenue Ads Rule ?

### ISSUE THREAD

**Issue by lyrnya** [hectorm/hblock#160]
[AWAvenue Ads Rule](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/main/assets/README_en-US.md) is one of the best blocking rules for Chinese ads.

Currently, hblock has missed some Chinese ads. I merged hblock with AWAvenue to remove duplicates (hosts) and found that there were about 300 more hosts rules.

AWAvenue Ads Rule supports multiple formats such as hosts, adblock, adguard, etc.

Hope that AWAvenue Ads Rule can be merged into hblock.

**Comment by hectorm** [comment]
Done!
