### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by mikropsoft** [hectorm/hblock#162]
As shown in the image, the trafficmanager.net rule is causing issues for many domains. For example, even dotnet.microsoft.net is being blocked (mostly Microsoft services). Additionally, you can check this; the blocked and problematic ones are displayed under the 'blocked by cname or ip' response.

![Ekran Görüntüsü (92)](https://github.com/user-attachments/assets/154e03b6-215f-422d-8b71-cbabc27825dc)

---

![Ekran Görüntüsü (93)](https://github.com/user-attachments/assets/020d7df8-f4a7-4863-b2bf-00f4c5a3c9f0)

**Comment by hectorm** [comment]
Thanks for the report, it has been fixed in easylist/easylistchina#399 and I have just regenerated the lists.
