### ISSUE TITLE
False Positive for Kiwi.com on mobile app

### ISSUE THREAD

**Issue by VIVRICCARDO** [hectorm/hblock#164]
Hello there
I am reporting a false positive for Kiwi.con mobile app. The blocklist blocks all the necessary links and the app fails to open. It works fine in the website version though.

Thanks for resolving it.

**Comment by hectorm** [comment]
Hi, could you please provide the domain of some of these blocked links so I can trace their source?

`kiwi.com` is not blocked, so it must be a different domain that the app is using. The only related domain I see being blocked is `loglady.kiwi.com`, which I don't know if is a problem for the app to work. You can try adding this domain to the allowed list and check.

**Comment by VIVRICCARDO** [comment]
Sure. I am sending you the screenshot of the logs. I see the website skypicker.com being blocked by hblock. 
![WhatsApp Image 2024-08-16 at 11 46 25_cc93f6a3](https://github.com/user-attachments/assets/d418c400-65b6-4fed-9055-b66ebc8b9073)


Let me know if it helps. And thanks for the wonderful work. hblock has been my blocklist for over a year now.

**Comment by hectorm** [comment]
Which of these domains would need to be allowed for the app to work? Check them one by one to find the minimum required.

**Comment by VIVRICCARDO** [comment]
I have no idea how, but the app is function all good now. I reinstalled the app and the re-enabled the hblock blocklist. Its functioning all fine now. But thanks for the immediate help. Much appreciated! 🤍

**Comment by hectorm** [comment]
I'm glad it's fixed, thanks for your kind words!
