### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by argosputnik** [hectorm/hblock#165]
**Describe the bug:**
Error 404 when running script
'/tmp/hblock.#1' 'https://raw.githubusercontent.com/hectorm/hblock/v3.4.5/resources/systemd/hblock.{service,timer}' \
  && echo '45980a80506df48cbfa6dd18d20f0ad4300744344408a0f87560b2be73b7c607  /tmp/hblock.service' | shasum -c \
  && echo '87a7ba5067d4c565aca96659b0dce230471a6ba35fbce1d3e9d02b264da4dc38  /tmp/hblock.timer' | shasum -c \
  && sudo mv /tmp/hblock.{service,timer} /etc/systemd/system/ \
  && sudo chown 0:0 /etc/systemd/system/hblock.{service,timer} \
  && sudo chmod 644 /etc/systemd/system/hblock.{service,timer} \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable hblock.timer \
  && sudo systemctl start hblock.timer

**Steps to reproduce:**
Ran script at command line in Ubuntu and received error 404 page not found.
Receive same error when I open a browser and try to go to https://raw.githubusercontent.com/hectorm/hblock/v3.4.5/resources/systemd/hblock.{service,timer

**Expected behavior:**
It is supposed to successfully run the script so the timer can be installed and configured

**Environment:**
Ubuntu 24
Firefox

**Comment by hectorm** [comment]
It's expected that you can't open that URL in your browser, the command uses the [URL globbing](https://everything.curl.dev/cmdline/urls/globbing.html) feature of cURL to download two files, `hblock.service` and `hblock.timer`.

If the version of cURL you are using does not support URL globbing, you can always manually download both files and move them to the correct location.
