### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by mikropsoft** [hectorm/hblock#166]
The address merchantpool1.epicgames.com is being blocked. This appears to be due to the rule named ||fpt.microsoft.com^. Epic Games purchases are being blocked.

**Comment by hectorm** [comment]
This domain is listed in [EasyPrivacy](https://github.com/easylist/easylist/blob/6b0a7ed80d6c92cd4a41d6b01fd11120685ca513/easyprivacy/easyprivacy_specific.txt#L559), you should report this upstream and if it is removed it will be automatically removed from hBlock.
