### ISSUE TITLE
Are these domains possibly transcribed inaccuracies?

### ISSUE THREAD

**Issue by 217heidai** [hectorm/hblock#169]
Are these domains([hosts adblock](https://hblock.molinero.dev/hosts_adblock.txt)) possibly transcribed inaccuracies?
domian list:
```
46186911.vtt
80055404.vtt
afahivar.coom
aistekso.nett
cbyqzt.xy
grid-bidder.criteo
pgl.example0101
test.vast
zupee.cim
```

**Comment by hectorm** [comment]
Probably yes, most of these domains come from AdGuard and EasyList, what I recommend is to report this to the original sources.
