### ISSUE TITLE
[Help] Can WHITELIST be fetched via url?

### ISSUE THREAD

**Issue by AdroitAdorKhan** [hectorm/hBlock#17]
I want to fetch whitelist from url, and use with hBlock. Is there any way to do that?

Thanks for this great script, btw! :)

**Comment by hectorm** [comment]
hBlock by itself doesn't support fetching the whitelist from an URL, but since it accepts an string input you can do something like:

```
hblock -W "$(curl -fsS https://example.com/whitelist.txt)"
```

**Comment by AdroitAdorKhan** [comment]
Thanks! Doesn't it support simple domain whietlisting? Like if i want to block `m.facebook.com`, in my text file `m.facebook.com` will be there...but it seems to block all domains likely by the same name! 

Care to explain whitelisting method?

**Comment by hectorm** [comment]
The whitelist consists on whitespace separated [POSIX basic regex](https://en.m.wikibooks.org/wiki/Regular_Expressions/POSIX_Basic_Regular_Expressions) entries. Here are some examples:

```
\.com$ -> all domains that ends with '.com'.
^example -> all domains that starts with 'example'.
^sub\.example\.org$ -> domain 'sub.example.org'.
```

**Comment by AdroitAdorKhan** [comment]
Thanks! :)
