### ISSUE TITLE
Unblock m.stripe.com

### ISSUE THREAD

**Issue by rusticadam** [hectorm/hblock#170]
m.stripe.com should not be blocked as it is necessary for payment system

**Comment by hectorm** [comment]
That domain is currently listed on the symbuzzer/Turkish-Ad-Hosts list, could you take a look at this @symbuzzer?

**Comment by symbuzzer** [comment]
@hectorm removed, thanks

**Comment by hectorm** [comment]
Thanks for the quick response!
