### ISSUE TITLE
CoinBlockerLists moved to GitLab

### ISSUE THREAD

**Issue by KonoromiHimaries** [hectorm/hBlock#21]
![2018-07-21-hectorm_hblock_ improve your security and privacy by blocking ads tracking and](https://user-images.githubusercontent.com/5884000/43038994-2b773e06-8d24-11e8-83b1-129020a177dd.png)
https://gitlab.com/ZeroDot1/CoinBlockerLists

**Comment by hectorm** [comment]
I updated the mirrors a few days ago (https://github.com/hectorm/hmirror/commit/3e2cdc0c0f836b3685f3dcaae20ff915650e82f8), but I forgot to update the readme. Thanks!
