### ISSUE TITLE
Problem making package

### ISSUE THREAD

**Issue by JustMeErazem** [hectorm/hblock#24]
I'm maintaining your package for the Arch User Repository and have recently come across a problem that was successfully fixed with the help of the community, but a member has advised me to tell you about problems in your Makefile. I am by no means an expert on this (and don't fully understand what they suggest), so I will point you to this forum topic: https://bbs.archlinux.org/viewtopic.php?id=244994

**Comment by hectorm** [comment]
Hi, I have solved these problems, thank you very much for reporting them.

**Comment by JustMeErazem** [comment]
Hi, thank you for solving them :)

I'm guessing I can revert to properly making the package (without manually moving files) in the next release, right?

**Comment by hectorm** [comment]
I think you could use the Makefile again, but if you have any other problem do not hesitate to report it.

**Comment by JustMeErazem** [comment]
Builds properly, so I've just pushed it. Thanks again!
