### ISSUE TITLE
Please add antipopads list to source.

### ISSUE THREAD

**Issue by sivajipro** [hectorm/hblock#25]
https://github.com/Yhonay/antipopads

**Comment by hectorm** [comment]
Hi, thanks for the recommendation.
I just created [a mirror](https://github.com/hectorm/hmirror/commit/2def6ffef3b00ab2e1d4d50ac1bc3ed0fdd2e6bf) and will check for a few days that it does not have false positives before adding it.

**Comment by sivajipro** [comment]
Thanks.
