### ISSUE TITLE
Improvement : is there a quick way to turn hblock off and on?

### ISSUE THREAD

**Issue by arcolinuxz** [hectorm/hblock#26]
Is there the option to tell 
`hblock on`
`hblock off`

I have an issue when downloading from sourceforge. 
I want to quickly test if it is not hblock blocking the server.

Will the original hosts file be put back?

**Comment by hectorm** [comment]
The fastest way to do this with hBlock would be to overwrite your configuration with environment variables.

 * **On:** `HBLOCK_SOURCES='' hblock`
 * **Off:** `hblock`

**Comment by Bhooty** [comment]
this should on the front page :(
its a vital info

**Comment by hectorm** [comment]
Done (261850d763e44dbb7ce705e85e2e254fa1442d3d).
