### ISSUE TITLE
improvement: latest version

### ISSUE THREAD

**Issue by illucent** [hectorm/hblock#27]
Please consider my idea to add 'latest version' release for semver compatibility, so that not to add versions manually.
eg.

```
curl -Ls -o /dev/null -w %{url_effective} https://github.com/docker/compose/releases/latest
```

returns latest version ```v<sem_version>``` automatically

```
curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/hectorm/hblock/releases/latest
```

**Comment by hectorm** [comment]
I just created a release through the GitHub UI, is this okay now?

**Comment by illucent** [comment]
yes, thanks a lot
