### ISSUE TITLE
Support from hostsVN - advertising block of Vietnam

### ISSUE THREAD

**Issue by bigdargon** [hectorm/hblock#28]
Hello!

I am from Vietnam, I have a project `hostsVN` for the purpose of blocking ads and tracking from advertisers from Vietnam. Wishing to support ad blocking projects that support blocking domains in Vietnam, so I created this issue hoping you will merge with hostsVN. The project has been maintained for more than 1 year and continuously updates new domain names.

Github: https://github.com/bigdargon/hostsVN/

Some sources use hostsVN:
- https://abpvn.com/android/
- https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/2437fd7f0b9586ef53a417dd63a59deac43452b0/Filters/filter.template#L92
- https://github.com/StevenBlack/hosts/releases/tag/2.5.0
- in `nextdns` lists

The hosts file I categorized only includes domain name blocking ads and tracking in Vietnam. I hope you just need to merge this file. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN

Thanks you!

**Comment by hectorm** [comment]
Hi, I added your list to hMirror (https://github.com/hectorm/hmirror/commit/6f6c9165762e636892bbeabd14dda1456d9b49cc) and it will be available on hBlock in the next version. Thanks!
