### ISSUE TITLE
Version 2.1.3

### ISSUE THREAD

**Issue by arcolinuxz** [hectorm/hblock#31]
I just dropped from 150.000 blocked domains to 116.000 domains on ArcoLinux

I suppose you know why that is

**Comment by hectorm** [comment]
I have decided to remove the anudeepND list because it contains false positives. This is not the first time that it has happened with this list.

If it does not cause you problems you can manually add it again.

**Comment by arcolinuxz** [comment]
ok thanks for letting me know
I will update the package and put it out there for our users
