### ISSUE TITLE
distinguish "vortex-win.data.microsoft.com"

### ISSUE THREAD

**Issue by beerisgood** [hectorm/hblock#32]
While _v10c.vortex-win.data.microsoft.com_ is for Diagnostics data Telemetry, the domain _de.vortex-win.data.microsoft.com_ is for **Microsoft Defender Advanced Threat Protection** - while the prefix (in this case ".de") is country specific.

So please remove

- vortex-win.data.microsoft.com

from your list.

Source: https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints

**Comment by hectorm** [comment]
Thanks for the notice.

I don't keep a public whitelist, instead I prefer to contact the blacklists' authors if I find a false positive.

In this case the domain is listed in [someonewhocares.org/hosts/](https://someonewhocares.org/hosts/), you should contact the author to solve this problem. This way all projects that make use of that blacklist will benefit, including hBlock.

**Comment by beerisgood** [comment]
Done: I will post the answer here

**Comment by beerisgood** [comment]
The author fix it!
