### ISSUE TITLE
apprep.smartscreen.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [hectorm/hblock#33]
*.smartscreen.microsoft.com* is used for Windows Defender Smartscreen which is a security feature and not telemetry.

Please unblock it.

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions

**Comment by hectorm** [comment]
Thanks for the notice.

As mentioned in a previous issue (https://github.com/hectorm/hblock/issues/32#issuecomment-569549553), I don't maintain a public whitelist.

In this case the domain is listed in [someonewhocares.org/hosts](https://someonewhocares.org/hosts), you should contact the author to solve this problem.

**Comment by beerisgood** [comment]
Let's see how he will handle it: https://github.com/StevenBlack/hosts/issues/1134

**Comment by hectorm** [comment]
Could you contact the autor of someonewhocares.org about this problem?

Also what are the implications of blocking this domain?

**Comment by beerisgood** [comment]
I already send him a mail (see the linked post).

apprep.smartscreen.microsoft.com is part from Windows SmartScreen (Cloud analyse) which protect Microsoft Edge & also Windows itself against Malware.

**Comment by hectorm** [comment]
So if this domain is blocked, does Windows SmartScreen stop working properly? I haven't been able to verify this because I haven't used Windows as my daily driver for years.

Let's see what the blacklist author says.

**Comment by beerisgood** [comment]
The dev fix it and is no longer in your list.
