### ISSUE TITLE
telecommand.telemetry.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [hectorm/hblock#34]
*telecommand.telemetry.microsoft.com* is used by Windows Error Reporting and isn't telemetry.

So please unblock it

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions

**Comment by hectorm** [comment]
Thanks for the notice.

As mentioned in a previous issue (https://github.com/hectorm/hblock/issues/32#issuecomment-569549553), I don't maintain a public whitelist.

In this case the domain is listed in [someonewhocares.org/hosts](https://someonewhocares.org/hosts) and [github.com/StevenBlack/hosts](https://github.com/StevenBlack/hosts), you should contact the authors to solve this problem.

**Comment by beerisgood** [comment]
Sadly the StevenBlack dev have no interest in fixing that: https://github.com/StevenBlack/hosts/issues/1135#issuecomment-578448539

**Comment by beerisgood** [comment]
As i already write, you can't send data from Windows Error Reporting to Microsoft so they can't fix your problems.

**Comment by hectorm** [comment]
I'm sorry, but since hBlock generates the blacklist from multiple sources, removing a domain would mean having to maintain a whitelist, and in this case I don't think the work it would take is justified.

You can either add the domain to your own whitelist or stop using the sources that are problematic for you.

**Comment by hectorm** [comment]
I would like to add that I've in mind at some point to add remote whitelist sources as is being done with blacklists, this would make the task easier, because currently if I want to add a domain to hBlock's whitelist I've to modify the script. However, I haven't had time to work on this yet.
