### ISSUE TITLE
No hash available for specified version

### ISSUE THREAD

**Issue by jameswilliams1** [hectorm/hblock#35]
I know the readme provides a hash in the install section script but it would be good to host a copy of this at the same place as the script (e.g. https://raw.githubusercontent.com/hectorm/hblock/v2.1.4/hblock.sha512 or something like that). Lack of a hash available through a URL makes this project hard to use in automated scripts (as someone has to check the readme when there's an update instead of being able to bump the version number in the URL and have it find the new hash also). I'm trying to write an Ansible role to install and configure this currently and this is the issue I have ran into, most people wouldn't deploy anything on their server without at least a hash check so this would be a really good feature.

**Comment by hectorm** [comment]
Wouldn't it be safer to specify directly in your code the expected hash for each release? Because if this repository is compromised, the attacker could simply update the file with the hash.

**Comment by jameswilliams1** [comment]
> Wouldn't it be safer to specify directly in your code the expected hash for each release? Because if this repository is compromised, the attacker could simply update the file with the hash.

I see your point, but in that case the readme would also be compromised. The main thing was that I normally have a script get the hash from some known location (changing only say the version number each time) then use that same has for all future downloads on other machines (not necessarily getting the hash and the download at the same time). I realise it's a small issue just it would be nice seeing as the hash is being calculated anyway with each update, to also upload it to github.

**Comment by hectorm** [comment]
> I see your point, but in that case the readme would also be compromised.

The readme is not meant to be automatically consumed by any process, so it is not something I worry about in the scenario of a compromission.

> then use that same hash for all future downloads on other machines (not necessarily getting the hash and the download at the same time)

If the hash is cached I see the benefit of your suggestion.

If I generate a `SHA256SUMS` file with the following content will it solve your problem?
```
a379434ebd58b0b976244d568a299318aa24e7be8d6795b5f8224bad3f4b44b8  hblock
```

**Comment by jameswilliams1** [comment]
> > I see your point, but in that case the readme would also be compromised.
> 
> The readme is not meant to be automatically consumed by any process, so it is not something I worry about in the scenario of a compromission.
> 
> > then use that same hash for all future downloads on other machines (not necessarily getting the hash and the download at the same time)
> 
> If the hash is cached I see the benefit of your suggestion.
> 
> If I generate a `SHA256SUMS` file with the following content will it solve your problem?
> 
> ```
> a379434ebd58b0b976244d568a299318aa24e7be8d6795b5f8224bad3f4b44b8  hblock
> ```

That would be great. Would that be a per release file or maintained as the hash of the current release only?

**Comment by hectorm** [comment]
My plan is to create that file inside the repository and update it for each release.

The file will be available from the following URL:
```
https://raw.githubusercontent.com/hectorm/hblock/v2.1.4/SHA256SUMS
```

I prefer this way instead of uploading the file using the [GitHub releases tab](https://github.com/hectorm/hblock/releases) because I don't like to depend on any GitHub features.
