### ISSUE TITLE
Solus

### ISSUE THREAD

**Issue by Bhooty** [hectorm/hblock#36]
Tried in solus 
Hblock edits the hosts file and adds the blocklists 
But doesn't create the hblock.d folder thus no whitelist or blacklist file 
I manually created and tried adding one domain from blocklist to whitelist 
Then refreshed the hosts file 
Although in terminal it shows 1less domain is added, the whitelist domain isn't removed from blocklist 
Hope to see a working version soon 😖

**Comment by hectorm** [comment]
I haven't used Solus, but hBlock should work fine in that distro.

To help you, please answer the following questions:
 * Which version of hBlock are you using?
 * Have you made any modifications to the script?
 * Could you share the contents of the `/etc/hblock.d/` directory and the terminal output?

**Comment by Bhooty** [comment]
It works fine 
But whitelist and blacklist doesn't seem to work :(
Installed using the cmd in the github page 
It used to work on ubuntu and manjaro 
I will try to create a video and give

**Comment by hectorm** [comment]
Answering the questions I've asked you should be enough, there's no need for a video.

**Comment by Bhooty** [comment]
On solus there is no usr/local/bin under which hblock is installed and the terminal was exiting 
So i editing cmd to usr/bin/ and it installed but it didn't created the etc/hblock.d folder 
So after I browsed some sites decided to create it and created to files inside it "whitelist.list" and "blacklist.list" 
Then went to usr/bin/hblock and mentioned the directory for the two files 
Then I ran hblock in terminal 
It modified the hosts file 
Now my main problem is if I edit the whitelist and write one of the domain from the edited hosts file 
And again hblock it shows it wrote in hosts without one domain from previous but still the domain is not accessible 
So I checked hosts again 
It seems the domain isn't removed from hosts 
And if i delete it manually and update again it again comes back 
And hblock -w and hblock -b and others not work 
Some work though

**Comment by hectorm** [comment]
> On solus there is no usr/local/bin under which hblock is installed and the terminal was exiting

Although the directory `/usr/local/bin/` does not exist by default in Solus, you can create it.

>  So i editing cmd to usr/bin/ and it installed but it didn't created the etc/hblock.d folder

The `/etc/hblock.d/` directory is not created by the installation command in the readme, it's not a problem, you can create it and hBlock will use it.

If you don't answer the questions I asked, I can't help you.

**Comment by Bhooty** [comment]
I think i answered everything 
Latest version which the command auto pulls 
Just modifed it like i said in the previous comment 
Nothing to share the content, I just created two files blacklist.list and whitelist.list 
Will share the terminal output later as it nighttime now :(

**Comment by hectorm** [comment]
Closed for inactivity.

**Comment by tillcash** [comment]
Which version of hBlock are you using? **2.1.5**
Have you made any modifications to the script? **No**
Could you share the command you're running and the terminal output? **https://i.imgur.com/3QoT3jB.png**
Could you share the contents of the /etc/hblock.d/ directory? **No directory**
