### ISSUE TITLE
Curl error for hblock v215 on kali linux

### ISSUE THREAD

**Issue by vdbhb59** [hectorm/hblock#37]
Hi Mate,
I have been using 2.1.3 and the previous builds as well. However, today when I updated to 2.1.5, since then I am facing the following error: `curl: (3) URL using bad/illegal format or missing URL.` Error snap below. My system is:

> 5.4.0-kali3-amd64 Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/60728004/75458899-9925cf80-594c-11ea-89ae-010b9eccb55d.png)
Please let me know if I am missing anything or is this actually a bug?

`/usr/local/bin/hblock`

```
!/bin/sh
# Version:    2.1.5
```
Danke mate. :)

**Comment by hectorm** [comment]
I see that you are using a source that is not included by default, however, in the terminal I see that hBlock says that it is using the builtin list, which means that possibly the script has been modified.

The error that is occurring is because cURL is receiving a malformed URL.

Could you share the full contents of the script?

**Comment by vdbhb59** [comment]
Sure. I will share tomorrow as my PC is not turned on. Also, yes I have modified the script to publish my list in headers and comments. Just to say, I have been using the same script earlier as well. It is just that I received this error after updating to 2.1.5.

For the source link, I gave this snapshot as an example. I tried it with around 5-6 different links, and with your default script without changing anything, but it did not work. This was not the case with earlier version.

Apologies for writing so much here, even before giving the script, just that in case if I don't get the chance to write tomorrow, so covering that part now.

Thanks for your patience mate. 😃

**Comment by hectorm** [comment]
Perfect, I'll be waiting for the script. It would be helpful if you confirm if with the original version of the script this error also occurs.

In addition, hBlock also supports having your own sources list in an external file so you don't have to modify the script. Just create the `/etc/hblock.d/sources.list` file and put each source on a new line.

**Comment by vdbhb59** [comment]
@hectorm yes, happens with original script too. I actually started getting error on 2.1.3 first and then I visited your Git to find 2.1.5 is present. So I updated to 215. Then I ran the original script and this error happened. So I uninstalled hblock from every place. I rebooted as well to ensure it was not the cause. Then I reinstalled and ran the original script again, and again the same error.

**Comment by hectorm** [comment]
Could you please run `sh -x "$(command -v hblock)" -O /dev/null` and provide the full command output?

**Comment by vdbhb59** [comment]
Sorry to be late. I tried the following:
1. Deleted all files related to hblock.. Paths:
 a. `/usr/local/bin/hblock`
 b. `/etc/systemd/system/timers.target.wants/hblock.timer`
 c. `/etc/systemd/system/hblock.service`
I had thought it was cause I had your `systmd` installed as well, may have caused an issue, so deleted all, rebooted, and installed just the `2.1.5 normal installer`.
2. After that without changing any details in `/usr/local/bin/hblock`, I ran `hblock` as root, and it worked.
3. However the moment I updated some URLs in `/usr/local/bin/hblock`, and ran "`hblock`" as root again, I faced the same `curl 3` error.

Attached is the script that I used after adding few URL's (just few out of many I have) and the 
verbose log as requested.
`sh -x "$(command -v hblock)" -O /dev/null`
[hblock.txt](https://github.com/hectorm/hblock/files/4267933/hblock.txt)
[verbose log.log](https://github.com/hectorm/hblock/files/4267934/verbose.log.log)

**Comment by hectorm** [comment]
I see the error, you are using CRLF line endings in a shell script.
```shell
$ awk '/\r/' ./hblock.txt
	http://mirror1.malwaredomains.com/files/immortal_domains.txt
	http://mirror1.malwaredomains.com/files/justdomains
	http://phishing.mailscanner.info/phishing.bad.sites.conf
	http://someonewhocares.org/hosts/hosts
	http://someonewhocares.org/hosts/zero/hosts
```

To fix it, convert all line endings to UNIX format.
```shell
$ tr -d '\r' < ./hblock.txt > ./hblock.fixed.txt
```

**Comment by vdbhb59** [comment]
Apologies if I sound stupid. This is the first time I am trying this, and I am not fully aware of how to go about it. Where should I push these "awk... " and "tr -d...." lines? In /usr/local/bin/hblock file, and after
BUILTIN_FOOTER=''
BUILTIN_SOURCES=$(cat <<-'EOF'

**Comment by vdbhb59** [comment]
@hectorm Also, I was using this same format and same URL earlier on 2.1.3 and never faced this issue.

**Comment by hectorm** [comment]
I don't know what you were doing on 2.1.3, but I guarantee that this problem has nothing to do with that.

Basically in Unix-like operating systems the lines are terminated with the `\n` character (LF), while in Windows the lines are usually terminated with the `\r\n` characters (CRLF).

Shell scripts don't support Windows style line endings and the editor you are using to modify the script may not be configured to use UNIX style line endings.

The command I wrote above (`tr -d '\r'`) is to remove all the `\r` characters from your script, which are causing the problem. You don't have to add it to any part of the script, just use it in your terminal to fix the modified script.

**Comment by vdbhb59** [comment]
Thanks, works now. I seriously need to learn all these a bit better.
For 2.1.3, I was on it for around 5 weeks, or so now. Did not have this error at all, and I was using many of the same links. Only added few new ones. Maybe they were the cause.
Thanks again for the help mate. :)
