### ISSUE TITLE
HowTo add hosts in correct way?

### ISSUE THREAD

**Issue by nan0viol3t** [hectorm/hblock#38]
Hello, how should I add hosts entries in a correct way to /etc/hosts, so hblock want remove entries while running/generating that file. I tried by whitelist but thats not an working solution.
-- If I want declare/assign IP to host name (which host file is for) it will be removed from /etc/host in next hblock run/update. I cant whitelist it, as host declaration need to be in that exact file "/etc/host" as its where other programs looks for... and if I edit hblock script, it will be updated with Os update (arcolinux)... So, how to approach ?

**Comment by hectorm** [comment]
If you create the `/etc/hblock.d/footer` file, hBlock will append its contents to the `/etc/hosts` file on every run.

**Comment by nan0viol3t** [comment]
Thank you for quick response and help. Works great with footer file and somehow I wasnt able to find that info in README or use cases with footer out there (net) - looks like I did not search enough this time. And of course big THANK YOU for hblock - its great !
