### ISSUE TITLE
s.youtube.com

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#40]
This domains has been breaking Youtube recommendations and saving items to history

**Comment by hectorm** [comment]
This domain is listed in [someonewhocares.org/hosts](https://someonewhocares.org/hosts). On that list there is a comment that says the following:

> Blocking this will interfere with video watching history

It seems that the author is aware of this problem. I suggest you contact him if you consider that this domain should not be blocked.

**Comment by p1r473** [comment]
Thanks, I emailed him
Please consider removing on your end too
