### ISSUE TITLE
forms.gle - False Positive

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#41]
This domain is just Google Forms.

**Comment by hectorm** [comment]
As mentioned in a previous issue (https://github.com/hectorm/hblock/issues/33#issuecomment-578492913), I don't maintain a public whitelist.

This domain is listed in [phishing.army](https://phishing.army/), you should contact the author to solve this problem. This way all projects that make use of that blacklist will benefit, including hBlock.

**Comment by p1r473** [comment]
No problem
Reporting just in case you want to remove from blacklist
I contacted the author there too
