### ISSUE TITLE
socialize.us1.gigya.com

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#42]
Hi, you are blocking the following domains:

socialize.us1.gigya.com

These domains break logging into iRobot app on Android, and starting iRoomba vacuum from Google Home

**Comment by hectorm** [comment]
As mentioned in a previous issue (https://github.com/hectorm/hblock/issues/33#issuecomment-578492913), I don't maintain a public whitelist.

This domain is listed in [lightswitch05's hosts](https://github.com/lightswitch05/hosts) and in this case I'm not so sure that this domain should be removed but if you consider that it's a mistake you should contact the author.

**Comment by p1r473** [comment]
No problem
Just reporting it in case you wish to remove from blacklist.
I contacted the author too.
