### ISSUE TITLE
does hblock check if remote hosts file size has changed since previous update?

### ISSUE THREAD

**Issue by rugabunda** [hectorm/hblock#46]
does hblock check to see if remote hosts files on remote server have changed before downloading, thus preventing the download of duplicates and speeding up processing? if not, please consider this a feature request.

One must maintain copies of the 1. files or 2. hashes on the system and compare the hash or whatever, diversion.ch does this effectively.

**Comment by hectorm** [comment]
Although I appreciate the benefit of this feature I think it is outside the scope of the project, as I want to keep this script as simple as possible.
