### ISSUE TITLE
financialprovider-logos.platform.intuit.com

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#47]
False positive: This domain is used for showing logos of financial providers on the Mint platform. With this domain blocked, the logo doesn't show up.
![image](https://user-images.githubusercontent.com/9235633/79177983-0218b800-7dd2-11ea-9c91-8aa832bbd371.png)

**Comment by hectorm** [comment]
It looks like it was solved upstream, so I'm closing the issue. Thanks for the notice.
