### ISSUE TITLE
edge.activity.windows.com

### ISSUE THREAD

**Issue by KLGIT886** [hectorm/hblock#51]
edge.activity.windows.com
Edge browser uses the activity.windows.com domain to sync browser data
It should not be disabled

**Comment by hectorm** [comment]
My blocklist is generated from multiple sources and I don't maintain a public whitelist.

In this case the domain is listed in [lightswitch05's hosts](https://github.com/lightswitch05/hosts) and if you consider that it's a mistake you should contact the author.

Anyway, thanks for reporting this.
