### ISSUE TITLE
Youtube ads not blocked properly

### ISSUE THREAD

**Issue by AndersonGI** [hectorm/hblock#52]
I know it is not an issue of your program directly, but I am writing here to let you know, maybe there is some host file that handle better youtube ads like the default ad-blockers from opera/vivaldi
![image](https://user-images.githubusercontent.com/9400376/88481008-a19c2980-cf2f-11ea-9568-cafe25776400.png)

**Comment by AndersonGI** [comment]
I found this one https://gist.github.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf, I am gonna test it

**Comment by AndersonGI** [comment]
I've found this one: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt

**Comment by hectorm** [comment]
YouTube ads are served from the same domains as the videos themselves, so blocking them with a hosts file is not reliable [1].

You can still use hBlock to generate your own blocklist and add the source you linked.

[1] https://discourse.pi-hole.net/t/how-do-i-block-ads-on-youtube/253
