### ISSUE TITLE
Blocked google icons

### ISSUE THREAD

**Issue by mindyourlifeguide** [hectorm/hblock#53]
When I use this filter, some of the icons are blocked in google services, namely google calendar / meet. I did not check the rest.
https://raw.githubusercontent.com/hectorm/hmirror/master/data/lightswitch05-ads-and-tracking/list.txt
![image](https://user-images.githubusercontent.com/35348648/89227243-fa318d80-d5e5-11ea-8b0c-9fdb86923e20.png)

**Comment by hectorm** [comment]
This is a known issue that has been discussed several times on the lightswitch05's hosts project (lightswitch05/hosts#136).

If you want Google Fonts to load you must add the `gstaticadssl.l.google.com` domain to the `/etc/hblock.d/whitelist.list` file.

**Comment by mindyourlifeguide** [comment]
> This is a known issue that has been discussed several times on the lightswitch05's hosts project ([lightswitch05/hosts#136](https://github.com/lightswitch05/hosts/issues/136)).
> 
> If you want Google Fonts to load you must add the `gstaticadssl.l.google.com` domain to the `/etc/hblock.d/whitelist.list` file.

Thanks! it's solved my problem)
