### ISSUE TITLE
Possible false positive: addevent.com www.addevent.com

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#54]
I believe addevent.com www.addevent.com may be false positives.
It is a service for sending calendar events to people, and they can accept the invite from Google Calendar/iCal etc.

I attended a virtual conference and this service is how they were sending out invites. I dont believe it is spyware or adware.

![image](https://user-images.githubusercontent.com/9235633/90894256-50e0ea80-e38e-11ea-8408-44ed7a4f271c.png)

**Comment by hectorm** [comment]
Neither `addevent.com` nor `www.addevent.com` are blocked in the default lists but `track.addevent.com` is. The latter may be necessary for the application to work.

If you consider it to be a false positive you should contact the authors of each list, as I do not maintain any public whitelist.

**Comment by p1r473** [comment]
@hectorm How do I find which list its from?

**Comment by hectorm** [comment]
My list is generated from several sources. [These are the default ones](https://github.com/hectorm/hblock#sources), you should check them out.

**Comment by p1r473** [comment]
Thanks, I've reported the issue upstream.
