### ISSUE TITLE
Can't download the zip, Windows 10 detects virus

### ISSUE THREAD

**Issue by Robin-Wils** [hectorm/hblock#55]
The windows version can't be downloaded on Windows 10, because Windows complains about virusses, probably a false positive.

**Comment by hectorm** [comment]
I'm sure it's a false positive.

It's possible to be related to this: https://www.bleepingcomputer.com/news/microsoft/windows-10-hosts-file-blocking-telemetry-is-now-flagged-as-a-risk/

Since there is nothing I can do to prevent this, I will close the issue. But thank you anyway for the notice.

**Comment by Robin-Wils** [comment]
Ok windows really forces this. I wrote a script around it.

I suddenly couldn't access any website. The DNSclient service was also suddenly eating all my CPU. Anyway here is the powershell script to activate hblock, but it will break your Windows system.

So this is a starting point for people who want to make hblock work on Windows. I might look into what causes it some day.


```powershell
# Prevent windows defender from blocking our host file
# See: https://www.bleepingcomputer.com/news/microsoft/windows-10-hosts-file-blocking-telemetry-is-now-flagged-as-a-risk/
Add-MpPreference -ExclusionPath "C:\Windows\System32\drivers\etc\hosts"

# Temporary exclude the installation files from windows defender
Add-MpPreference -ExclusionPath $env:USERPROFILE\Downloads\hosts

# Get hblock installation files
curl.exe https://hblock.molinero.dev/hosts_windows.zip --output $env:USERPROFILE\Downloads\hosts.zip
Expand-Archive $env:USERPROFILE\Downloads\hosts.zip $env:USERPROFILE\Downloads\hosts

# Install hblock
cmd.exe /c $env:USERPROFILE\Downloads\hosts\install.bat

# Remove temporary windows defender block
Remove-MpPreference -ExclusionPath $env:USERPROFILE\Downloads\hosts

# Remove installation files
Remove-Item -Recurse $env:USERPROFILE\Downloads\hosts.zip
Remove-Item -Recurse $env:USERPROFILE\Downloads\hosts
```

**Comment by hectorm** [comment]
The DNSclient service doesn't work properly with large hosts files.
https://github.com/StevenBlack/hosts/issues/93
https://github.com/StevenBlack/hosts/issues/710

**Comment by Robin-Wils** [comment]
Oof, that sucks. 

I moved to windows after around three years of using GNU/Linux. My GPU just doesn't works well in GNU/Linux, and I want to learn some things like 3D modeling which need the GPU. GPU passthrough didn't work on my system either.

Anyway, back to ublock origin it is then. Pi-hole can work too, in case anyone else on windows is reading this. Thanks for mentioning the DNSclient problem.

**Comment by hectorm** [comment]
Although I've not tried it, it seems that there is a workaround for Windows 10:

  1. From sysinternals.com download the latest version of AUTORUNS ... it doesn't require any installation.
  2. Run autoruns64.exe as ADMINISTRATOR and wait until it finishes it's scan.
  3. In the program menu under OPTIONS, uncheck the "Hide Windows Entries" option
  4. Go to the Services tab, scroll down to the Dnscache entry and clear (uncheck) the checkmark.
  5. You can FILE / SAVE, to save a copy of the new configuration settings.
  6. Close autoruns64, reboot and check the services manager -- DNS Client is disabled.

http://winhelp2002.mvps.org/hosts.htm

**Comment by Robin-Wils** [comment]
It is good to hear that there might be a fix. 
I think that this fix might break with updates or something, so I am going to use uBlock Origin for now. It is not perfect, but should do the job.
