### ISSUE TITLE
Geoffrey Frogeye's block list

### ISSUE THREAD

**Issue by fabianski7** [hectorm/hblock#56]
could you add that list?

https://hostfiles.frogeye.fr/

**Comment by hectorm** [comment]
Thanks for the suggestion.

I've created [a mirror](https://github.com/hectorm/hmirror/commit/d692a201e6490acc31ef33a6227f047ae53737fe#diff-b1e93c728922dd3ef846be708bcd7857) and will consider adding it by default if I don't find any false positives.

**Comment by hectorm** [comment]
Added in ee9c6e7d4ab746a2361666ab45ae9eba5e519f40.
