### ISSUE TITLE
false positive: ssl.bblck.me

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#58]
Hello,
You are blocking ssl.bblck.me which is hosting another blocklist
https://ssl.bblck.me/blacklists/hosts-file.txt
https://ssl.bblck.me/blacklists/domain-list.txt
Thanks

**Comment by hectorm** [comment]
It seems that this domain was added in [this commit](https://github.com/lightswitch05/hosts/commit/22d6780a86837a4443e5d6d79c647c457b8b5669) of the [lightswitch05's hosts repository](https://github.com/lightswitch05/hosts).

In this case I consider the blocking legitimate, as ssl.bblck.me is no longer active and could be taken by a malicious actor (see https://github.com/paulgb/BarbBlock/issues/34).

Anyway, thanks for reporting this.

**Comment by p1r473** [comment]
@lightswitch05 FYI, this domain is no longer resolving, and you might want to resolve it.

**Comment by lightswitch05** [comment]
Thanks for the ping @p1r473. My system requires 5 consecutive `NXDOMAIN` results over the course of several days before it gets automatically removed from the list. Looks like this one is on `#4` - so it should be removed either today or tomorrow

**Comment by p1r473** [comment]
@lightswitch05 would love if you shared that script so I may use it on my own lists!

**Comment by lightswitch05** [comment]
Unfortunately its closed source because its all junk and probably isn't very secure. Its got a database and is all very complicated and I don't like it. I do have a Java library for dealing with hosts files and doing DNS lookups: https://github.com/blocklist-tools/blocklist-tools
