### ISSUE TITLE
Blocked google icons

### ISSUE THREAD

**Issue by mindyourlifeguide** [hectorm/hblock#60]
Despite the fact that  **googleadapis.l.google.com**  is included in the whitelist, it is still blocked and is present in the host.
How to fix it? This happened after yesterday's update.

**Comment by hectorm** [comment]
You mean after upgrading hBlock to version 3.0.0?

This version introduces some breaking changes, in this particular case the file `/etc/hblock.d/whitelist.list` is now `/etc/hblock/allow.list`.

**Comment by mindyourlifeguide** [comment]
![image](https://user-images.githubusercontent.com/35348648/98643972-77347780-2338-11eb-9cae-ab2daa3f711b.png)
![image](https://user-images.githubusercontent.com/35348648/98645007-fd9d8900-2339-11eb-8def-dba61f222ae8.png)


The rest of the lists should also be moved to `/etc/hblock/ `?
Do they have the same names or do they also need renaming?
Where can I read about new locations and correct file names?

**Comment by hectorm** [comment]
Yes, the other paths have also changed.

You can check out the new paths by running `hblock --help` or by looking at the [documentation in GitHub](https://github.com/hectorm/hblock/blob/v3.0.0/hblock.1.md).

**Comment by mindyourlifeguide** [comment]
> Да, изменились и другие пути.
> 
> Вы можете проверить новые пути, запустив `hblock --help`или просмотрев [документацию на GitHub](https://github.com/hectorm/hblock/blob/v3.0.1/hblock.1.md) .

Thanks for the quick response!
This solved my problem - now everything works as it should)
Thanks!
