### ISSUE TITLE
quick enable/disable hblock

### ISSUE THREAD

**Issue by mindyourlifeguide** [hectorm/hblock#61]
Tell me how to quickly turn it on and off now? [This ](https://github.com/hectorm/hblock/issues/26)solution stopped working after version 3.0.

**Comment by hectorm** [comment]
This should work the same as before, by overwriting the `HBLOCK_SOURCES` environment variable.

* **Disable:** `HBLOCK_SOURCES='' hblock`
* **Enable:** `hblock`

```
[hectorm@hydrogen ~]$ HBLOCK_SOURCES='' hblock -qO-
# Generated with:  https://github.com/hectorm/hblock
# Blocked domains: 1

# BEGIN HEADER
127.0.0.1       localhost hydrogen
255.255.255.255 broadcasthost
::1             localhost hydrogen
::1             ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
ff02::3         ip6-allhosts
# END HEADER

# BEGIN BLOCKLIST
0.0.0.0 hblock-check.molinero.dev
# END BLOCKLIST
```

**Comment by mindyourlifeguide** [comment]
Not working.

![Peek 2020-11-12 10-37](https://user-images.githubusercontent.com/35348648/98915896-302eb980-24d3-11eb-9c0e-5299ae7465c8.gif)

**Comment by mindyourlifeguide** [comment]
I found [a way to disable ](https://github.com/hectorm/hblock/issues/57) hblock. 
`hblock -S /dev/null`
Is it possible to disable this or is it worth figuring out why that command (`HBLOCK_SOURCES='' hblock`) does not work?

**Comment by hectorm** [comment]
You can provide the output of the following command to know what is happening:

```sh
HBLOCK_SOURCES='' sh -x "$(command -v hblock)"
```

**Comment by hectorm** [comment]
However, the next version will support `-S none` to disable hBlock without having to resort to this type of workarounds.

This functionality is already implemented in the [dev branch](https://github.com/hectorm/hblock/tree/dev), but it is still experimental and subject to changes.

**Comment by mindyourlifeguide** [comment]
Here is the console output:
![Peek 2020-11-12 13-16](https://user-images.githubusercontent.com/35348648/98933581-81e23e80-24e9-11eb-80f3-269b2b4c8730.gif)

Then I will turn off the method above for now, and with the update I will switch to the official method.
Thanks!

**Comment by hectorm** [comment]
Could you please paste the terminal output instead of an image so I can read it in detail?

**Comment by mindyourlifeguide** [comment]
Of course, keep [logfile.txt](https://github.com/hectorm/hblock/files/5530453/logfile.txt)

**Comment by mindyourlifeguide** [comment]
Can I close this issue?

**Comment by hectorm** [comment]
Now I understand why it does not work, the presence of the `/etc/hblock/sources.list` file has priority over the environment variable.

This will be solved in the next version and since you have found a workaround, I consider the issue solved.

Thanks for reporting this.

**Comment by mindyourlifeguide** [comment]
Thanks you!
