### ISSUE TITLE
Script halts on "Matching hosts lines" with OpenBSD

### ISSUE THREAD

**Issue by pguizeline** [hectorm/hblock#63]
Hi!

I was trying the script on OpenBSD 6.8 and the script halts almost at the end, on "Matching hosts lines", is there any debug flag I can use to help?

Thanks!

**Comment by hectorm** [comment]
I wouldn't call it halt, it just takes longer on OpenBSD because GNU awk, sed and grep are much faster.

I just checked hBlock 3.1.1 on OpenBSD 6.8 and FreeBSD 12.2 and all the tests passed correctly.

**Comment by pguizeline** [comment]
I'm sorry, you're correct, just ran hBlock with just one small list and it ran with no issues. I guess I'm just using a lot of lists. Sorry for the false alarm!
