### ISSUE TITLE
Add an option to print the default sources

### ISSUE THREAD

**Issue by fhriley** [hectorm/hblock#64]
I am using hblock to download lists one at a time. I currently have a list of hblock's built in sources defined. It would be nice if I could call hblock with an option to get the built in sources so I always get the correct sources. Output that is URLs separated by newline would be perfect.

**Comment by KeyofBlueS** [comment]
Hi, You could try with:
`grep "https://raw.githubusercontent.com/hectorm/hmirror/master/data/" "$(which hblock)"`

**Comment by fhriley** [comment]
That will work, thanks!
