### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by therealthingy** [hectorm/hblock#65]
A HomeBrew Formula would make installing (and updating) hblock on macOs even more a breeze :)

**Comment by hectorm** [comment]
I agree that it would be very useful, unfortunately I don't have a macOS and I've never used Homebrew, so it would be difficult for me to maintain such formula. However I'm willing to help with whatever I can to anyone who wants to create and maintain it.

**Comment by hectorm** [comment]
I finally took the time to run macOS with KVM and created the formula (Homebrew/homebrew-core#68289).
