### ISSUE TITLE
Unable to make and install package on Debian Bullseye

### ISSUE THREAD

**Issue by Rotonen** [hectorm/hblock#66]
The .deb package for hblock cannot currently be built on Debian Bullseye.

```
$ make package-deb
PKG_VERSION='3.1.2' ./resources/packaging/deb.sh 'dist/packages/hblock-3.1.2.deb'
dpkg-buildpackage: info: source package hblock
dpkg-buildpackage: info: source version 3.1.2
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Héctor Molinero Fernández <hector@molinero.dev>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: dh-systemd (>= 1.5)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
make: *** [Makefile:173: dist/packages/hblock-3.1.2.deb] Error 3
```

That package has been folded into `debhelper` in version `9.20160709` of `debhelper`.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958585

Additionally when dropping the build time dependency on `dh-systemd`, the resulting .deb is not installable.

```
# dpkg -i dist/packages/hblock-3.1.2.deb
(Reading database ... 59729 files and directories currently installed.)
Preparing to unpack dist/packages/hblock-3.1.2.deb ...
Unpacking hblock (3.1.2) ...
dpkg: error processing archive dist/packages/hblock-3.1.2.deb (--install):
 unable to open '/usr/lib/systemd/system/hblock.service.dpkg-new': No such file or directory
Processing triggers for man-db (2.9.3-2) ...
Errors were encountered while processing:
 dist/packages/hblock-3.1.2.deb
 ```

Superficially that seems like a sort of a race condition, but I was not able to figure that one out.

**Comment by hectorm** [comment]
Thanks for the warning about the dropping of the `dh-systemd` package, I've just removed it from the build dependencies.

Could you confirm if the latest changes in the master branch solve your issues?

**Comment by Rotonen** [comment]
I am now able to `make package-deb` and install the resulting package on Bullseye.

That's a good workaround with the service installation skip.

Thank you.
