### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by obeho** [hectorm/hblock#67]
From Hosts Domains list please remove `www.csit.edu.in` . Its a genuine university website.

**Comment by hectorm** [comment]
The blocklist generated by hBlock comes from multiple sources and I don't maintain a public exception list.

In this case that domain comes from the "[Phishing Army](https://phishing.army/)" list, you should contact them and once the domain is removed from there it will also be removed from hBlock automatically.

**Comment by obeho** [comment]
> I don't maintain a public exception list

Didn't know that. You should probably mention it on the website or github. I see you have had to reiterate this point to several users here.

**Comment by btdmaster** [comment]
> > I don't maintain a public exception list
> 
> Didn't know that. You should probably mention it on the website or github. I see you have had to reiterate this point to several users here.

One more thing - please document how you find the source from which a domain is being blocked! It should help a lot when reporting false positives to list maintainers.

**Comment by hectorm** [comment]
Initially I didn't mention this because there weren't many requests of this kind and it was useful for me to know if a list had false positives but now it's becoming a burden for both parties, so I'll indicate this on the README.md and in the issue template.

**Comment by obeho** [comment]
Cool. You can close this issue when its done.
