### ISSUE TITLE
openSUSE package

### ISSUE THREAD

**Issue by Poorchop** [hectorm/hblock#69]
**Is your feature request related to a problem? Please describe:**
Not a problem, would just like a package for openSUSE.

**Describe the solution you'd like:**
Hblock available in the openSUSE Tumbleweed repos.

**Describe alternatives you've considered:**
Manual installation.

**Additional context:**
I'm also curious about how one would use this with a Pi-hole. Would you advise just manually copy/pasting the primary URLs from [the sources](https://github.com/hectorm/hblock/blob/master/SOURCES.md) into the block list field?

Thank you for your work on this project.

**Comment by hectorm** [comment]
Currently the Makefile can generate a RPM compatible with Fedora, CentOS and OpenSUSE, but contributing and maintaining such package in the official OpenSUSE repositories would take a long time. However I am willing to help anyone who wants to maintain it.

Regarding the Pi-hole question, you can add each source individually or simply add the nightly build that you can find [on the website](https://hblock.molinero.dev/).
