### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by Bhooty** [hectorm/hblock#71]
is there any ways i can change the sources?
i want to use a different list

**Comment by Bhooty** [comment]
Found it
edited hblock at /usr/bin/hblock
changed the sources to https://hosts.oisd.nl/
and save
then clear hosts using the command on front page and updated using hblock on terminal
and i get the list from oisd :D
Thanks for the great script :D 
Awesome job!!!!

**Comment by hectorm** [comment]
Instead of modifying the source code a better option is to create the `/etc/hblock/sources.list` file with the sources list.

In any case, thank you for your support!

**Comment by Bhooty** [comment]
> Instead of modifying the source code a better option is to create the `/etc/hblock/sources.list` file with the sources list.
> 
> In any case, thank you for your support!

I wanted to do this first
But i installed using the aur of archlinux package in manjaro
For some reason 
The folder isn't there

**Comment by hectorm** [comment]
If the `/etc/hblock/` directory doesn't exist, you can create it.

**Comment by Bhooty** [comment]
> If the `/etc/hblock/` directory doesn't exist, you can create it.

Oww
Didn't though it that way xD
Either way its solved 
I prefer the oisd list
List maintainer compiles other sources into one and is quick to fix false positive 
I always had problems with steven blocklist 
Thanks again 😅😅
