### ISSUE TITLE
More block lists featured on another GitHub page

### ISSUE THREAD

**Issue by LostAccount** [hectorm/hblock#72]
I am posting this in an effort to potentially expand, at your discretion, a list that I found on https://github.com/rimu/no-qanon

Adding this list of domains to hblock can potentially further enhance the user experience by blocking content that is essentially dangerous.

Again, I will leave this to your discretion but I for one would up vote the addition of this list of domains which appears to be regularly updated.

Kind regards
—Alex

**Comment by hectorm** [comment]
Even if I agree with the harm of such content I think it's outside of the scope of hBlock to block any political content by default. I'm only interested in blocking content related to malware and advertising.

I hope you understand my position on this and thanks for the suggestion anyway.

**Comment by LostAccount** [comment]
Thanks for the prompt reply. I absolutely understand your position and I respect the scope of the product as It relates to your specific goals. Thank you for considering and for the prompt reply. PS, I love your product, keep up the great work.
