### ISSUE TITLE
violation of license terms

### ISSUE THREAD

**Issue by trhr** [hectorm/hblock#73]
Hey, I didn't know the right way to submit this, but check out this project.

https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/blob/master/quantum_adlist.sh

That's your code. 

https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/issues/13

There's some other open source developers claiming that the dev on this project got honeypotted by them. He's asking for money to "keep the AI servers running."

I figured you'd want to know about this.

**Comment by hectorm** [comment]
Hi! I really appreciate you taking the time to let me know about this.

I was already aware that this project is using my code and I opened an [issue on their GitLab](https://web.archive.org/web/20210104101649/https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/issues/18) for them to [credit me](https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/commit/a774440252358362d9b0190928a8ddf3c9365c7b).

What I didn't know is that days later they deleted the issue and although I saved it on archive.org their response was not archived:
> ![](https://user-images.githubusercontent.com/852266/111065122-63e91280-84b8-11eb-9db0-d7ff96b4a1dc.png)

At that time their project was licensed under the GPLv3 and by simply crediting me I was fine with the situation but now I'm seeing that they have relicensed my code under The Unlicense, which is less restrictive than MIT.

I just opened an issue on their GitLab about this:
https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/issues/31

**Comment by hectorm** [comment]
They closed and removed the issue with the following response:
> ![](https://user-images.githubusercontent.com/852266/111076145-63b63a80-84eb-11eb-872c-f0acb9995f1a.png)

At least they have also removed all my code from their installer, so I no longer have any interest in them.
