### ISSUE TITLE
Parsing error on "hectorm/hmirror/master/data/adguard-simplified/list.txt"

### ISSUE THREAD

**Issue by pguizeline** [hectorm/hblock#74]
Hi!

I use hBlock to generate RPZ style blocklists on OpenBSD 6.9, using Unbound 1.13.1. I use the whole hBlock default lists, the only difference is that I manually use the original source links, and the only ones I use the hmirror links, are the ones that have a browser adblock style:

- adguard-simplified
- easylist
- easyprivacy
- ublock-abuse
- ublock-badware
- ublock-privacy
- ublock/list

I've noticed that the adguard-simplified list has a double entry on line 749/750 "4adtf.com" and "4adtf.com."

The dot in the end breaks unbound-checkconf. I've disabled that list only for the time being.

Thanks a lot for your work! This is an awesome script and it helps wonders! Specially hmirror for parsing the complex lists!

**Comment by hectorm** [comment]
Good catch! I've updated hBlock and hMirror to remove the ending dot from fully-qualified domain names.
