### ISSUE TITLE
HBlock on Safari

### ISSUE THREAD

**Issue by fabston** [hectorm/hblock#75]
Hi there,

I am using HBlock on Mac (installed using Brew) but it appears to be not working on Safari. At least when I run the check by visiting your website it states that I am not using HBlock. Is that a known issue or am I missing something?

Thanks for your help.

**Comment by hectorm** [comment]
It seems obvious, but have you run the `hblock` command after installing hBlock?

I just tested it in Safari on a macOS Big Sur and it worked correctly.

**Comment by fabston** [comment]
Yes I have done that already. On Chrome for example it works just fine. I’m using the M1 Model though.

**Comment by hectorm** [comment]
I don't have any M1 to test it, just a VM with Big Sur.

There doesn't seem to be a specific cause why Safari might be ignoring the `/etc/hosts` file but apparently [more people suffer from this problem](https://www.google.com/search?q=safari+ignores+hosts+file).

To find the cause, I recommend you remove from the `/etc/hosts` file all blocked domains with the `hblock -S none -D none` command and edit the file to try to manually block the `hblock-check.molinero.dev` domain, which is the one the hBlock website uses to check if it's enabled.

**Comment by fabston** [comment]
I tried that, on Chrome it works just fine, on Safari it seems to not work... Guess it is a Safari issue after all then.

**Comment by hectorm** [comment]
I'm going to close the issue as it's not an hBlock problem. Thanks for reporting it anyway.
