### ISSUE TITLE
content.ctfs.com

### ISSUE THREAD

**Issue by p1r473** [hectorm/hblock#76]
This domain is required for Canadian Tire Financial Services mobile app, or logging into Triangle Credit Card App.
This is not a malicious domain
I have reported this upstream but reporting here just in case you wish to whitelist
Thanks

**Comment by hectorm** [comment]
Hi, thanks for reporting it, did you get a response?

**Comment by p1r473** [comment]
Its still on a lot of adlists

**Comment by hectorm** [comment]
At least the only hBlock source that contains this domain is the [Geoffrey Frogeye's list](https://hostfiles.frogeye.fr/).

Although I've doubts that it's a false positive. This domain has a CNAME record to `h-canadiantire.online-metrix.net`, which belongs to ThreatMetrix, [a tracking company](https://www.propay.com/en-US/Developer/Boarding-ThreatMetrix).

```
$ dig content.ctfs.com @1.1.1.1

; <<>> DiG 9.16.18 <<>> content.ctfs.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15896
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;content.ctfs.com.		IN	A

;; ANSWER SECTION:
content.ctfs.com.	3590	IN	CNAME	h-canadiantire.online-metrix.net.
h-canadiantire.online-metrix.net. 20 IN	A	185.32.241.65

;; Query time: 9 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jun 22 21:02:38 CEST 2021
;; MSG SIZE  rcvd: 107
```

**Comment by p1r473** [comment]
Thanks, good find. I will close the ticket.
