### ISSUE TITLE
False positive: usefathom.com

### ISSUE THREAD

**Issue by JackEllis** [hectorm/hblock#77]
Hey hblock maintainers,

We spoke to the Pi-hole maintainers about some issues our customers (and their users) have been having, and they sent us here: https://blocklist-tools.developerdan.com/entries/search?q=usefathom.com

It looks like hBlock is blocking usefathom.com. We'd expect cdn.usefathom.com and img3.usefathom.com to be blocked, as that's third party, privacy-first analytics software, but not the root domain (usefathom.com).

Any chance you'd be able to unblock us?

Thanks,

Jack

**Comment by hectorm** [comment]
Currently the domain you indicate is not present in hBlock, you can verify it in the [last build](https://hblock.molinero.dev).
