### ISSUE TITLE
Parallel downloads of block lists

### ISSUE THREAD

**Issue by mindyourlifeguide** [hectorm/hblock#78]
Hey! Are you planning to implement parallel loading of block lists?

**Comment by hectorm** [comment]
It's a nice idea but not a priority at the moment. I'm going to leave this issue open to implement it at some point.

**Comment by hectorm** [comment]
Today I had the time to implement this feature in the [parallel-downloads](/hectorm/hblock/tree/parallel-downloads) branch.

It's experimental, not optimal and probably has bugs. I'll need a few more iterations until I feel comfortable enough to promote it to a stable release.

With the `-p` option you can set the maximum concurrency, at the moment the default value is `1`.

**Comment by hectorm** [comment]
Implemented in v3.3.0.

Happy holidays!
