### ISSUE TITLE
Append to instead of replace current `hosts` file

### ISSUE THREAD

**Issue by jeroen-s** [hectorm/hblock#79]

**Comment by lucserre** [comment]
As it is right now, when you run hblock for the first time after installing, any entries you have in your hosts file are lost, unless you have the foresight to add them to the header/footer before running it for the first time.

**Comment by hectorm** [comment]
Append instead of replace would not be compatible with how hBlock works because although the default behavior is to replace the hosts file it can actually generate blocklists [for almost any format](https://github.com/hectorm/hblock/tree/master/resources/alt-formats), so it cannot read the target file before because the format may be unknown.

**Comment by lucserre** [comment]
Thanks for taking the time for replying.  Perhaps I can suggest that if /etc/hblock/header doesn't exist (maybe it's the first time running hblock), you copy /etc/hosts to /etc/hblock/header by default?  This would prevent deleting user data without warning.  My hosts file contained custom entries that were lost by running hblock.   Just a thought.  Thanks!

**Comment by hectorm** [comment]
Sorry for the loss of your entries, but I think that many users don't use the header file and hBlock should not write any other file than the one indicated in the `--output` option as it would be a unintuitive behavior.

**Comment by lucserre** [comment]
Thank you again for your response.   Just something to consider: some might consider that overwriting existing user/system configuration files without warning unintuitive behaviour.  Thanks again, I really enjoy/appreciate hblock!

**Comment by hectorm** [comment]
I've added to the readme a warning about this fact to not catch anyone off guard. Regarding the append feature, I don't see it feasible to implement it, so I'm going to close this issue.

In any case, I appreciate @lucserre that you have shared your viewpoint on this matter. Thanks!

**Comment by lucserre** [comment]
Thanks for your consideration/time.
