### ISSUE TITLE
Please add Spotify

### ISSUE THREAD

**Issue by arturbrasil** [hectorm/hblock#80]
0.0.0.0 pubads.g.doubleclick.net
0.0.0.0 securepubads.g.doubleclick.net
0.0.0.0 http://www.googletagservices.com
0.0.0.0 gads.pubmatic.com
0.0.0.0 ads.pubmatic.com
0.0.0.0 spclient.wg.spotify.com

**Comment by hectorm** [comment]
The blocklist generated by hBlock comes from multiple sources and I don't maintain my own list. If you report this to one of my [sources](https://github.com/hectorm/hblock/blob/master/SOURCES.md) and they add these domains, they will be automatically included in hBlock.
