### ISSUE TITLE
Question : backup of /etc/hosts file

### ISSUE THREAD

**Issue by arcolinuxz** [hectorm/hblock#83]
Is it possible that the backup functionality is no longer there?
Is it now automatically?
Did the switch change?
It used to be hblock -b.

**Comment by hectorm** [comment]
I removed this feature in the version 3.0.0 of hBlock because it lacked basic functionality such as proper backup rotation and I considered that this task would be better suited to an external tool.

**Comment by arcolinuxz** [comment]
thanks for the response
