### ISSUE TITLE
Website Broken - trk.klclick.com

### ISSUE THREAD

**Issue by gyCfjSnO** [hectorm/hblock#85]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):
```trk.klclick.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail: Unable to unsubscribe from marketing emails I am receiving to my email address. Picture attached of my AdGuard Home blocking ```trk.klclick.com``` as the domain ```klclick.com``` is on a blocklist I am using. I crosschecked other lists using ```https://blocklist-tools.developerdan.com/entries/search``` which brought me to your list which has the domain blocked.

![image](https://user-images.githubusercontent.com/49738152/140669540-5670e828-cb43-46c9-bf9a-396342d2bb83.png)

**Comment by hectorm** [comment]
This domain is not currently blocked in hBlock, although it was blocked in the past.

![](https://user-images.githubusercontent.com/852266/140793017-c7ff581e-32ff-4d89-a4be-3bd5eea430e7.png)

**Comment by gyCfjSnO** [comment]
I am using AdGuard Home so it is picking up ```klclick.com``` on your Blocklist. My error for putting the subdomain.

![Uploading Screenshot_20211109-051032.png…]()

**Comment by gyCfjSnO** [comment]
@hectorm I am using AdGuard Home so it is picking up ```klclick.com``` on your Blocklist. My error for putting the subdomain.

![Screenshot_20211109-051032](https://user-images.githubusercontent.com/49738152/140803123-068c76a4-456d-4389-b584-a14a744e596b.png)

**Comment by hectorm** [comment]
Correct, that domain is blocked because it is present in [Peter Lowe's list](https://pgl.yoyo.org/adservers/). You should inform him about this and if he removes the domain it will be removed from hBlock as well.

**Comment by gyCfjSnO** [comment]
@hectorm Peter Lowe has advised not worth email them so no way of quickly informing them. What other solution do you propose?

> Unfortunately it's probably not worth submitting anything at the moment - spam has taken over. 10,000 mails a month to sift through, even with automated checking, is just too much extra. Fuckin spammers.

> Please send general stuff to pgl@yoyo.org or just fill out the comments form below.

> Ad server submission disabled until further notice.
> Thanks.

**Comment by hectorm** [comment]
I have successfully contacted him in the past, you should try.
