### ISSUE TITLE
Disable/Enable command added to hblock.molinero.dev 

### ISSUE THREAD

**Issue by LostAccount** [hectorm/hblock#87]
Reason for this request. I want to quickly go to hBlock's site, copy and paste the disable command, get something done and then turn it back on again.

Cheers

**Comment by hectorm** [comment]
Do you mean adding to the nightly builds website the command I mention in the project readme?

```sh
hblock -S none -D none
```

In that case I prefer not to clutter that website, instead I recommend you to create an alias on your system for this command.
