### ISSUE TITLE
False Positive: requestmetrics.com

### ISSUE THREAD

**Issue by federicotorrielli** [hectorm/hblock#89]
Hello,
I was trying to read the blog post found on hacker news [here](https://requestmetrics.com/web-performance/http3-is-fast) but seems blocked by hblock...

**Comment by hectorm** [comment]
It seems that AdGuard DNS is blocking that domain. If you think it is a false positive you should contact them and if they remove it from their list it will also be automatically removed from hBlock.

**Comment by federicotorrielli** [comment]
Ok, thanks!
