### ISSUE TITLE
Would it be a good idea to add the version to the /etc/hosts on line 3?

### ISSUE THREAD

**Issue by arcolinuxz** [hectorm/hblock#90]
![ArcoLinux-2021-12-25_17-42](https://user-images.githubusercontent.com/36679406/147389583-b13df668-215d-4d12-8afc-a697cfbaec69.jpg)

**Comment by arcolinuxz** [comment]
Thanks for maintaining this - even on Christmas Day
Best wishes and good health

**Comment by hectorm** [comment]
What do you think about a header like this?
```
# Generated with hBlock 3.3.0 (https://github.com/hectorm/hblock)
# Blocked domains: N
```
It's a good idea anyway, I will implement it.

**Comment by arcolinuxz** [comment]
super
sold

**Comment by erikdubois** [comment]
![ArcoLinux-2021-12-26_15-39](https://user-images.githubusercontent.com/10594806/147411476-5795d841-c7c5-4cf2-9e18-81175da7f06d.jpg)
Cool thank you

**Comment by hectorm** [comment]
Thanks to you for taking the time to try it out!
