### ISSUE TITLE
Block lists

### ISSUE THREAD

**Issue by Elimelech** [hectorm/hblock#93]
Can I connect my own blocking lists?
For example, I don't need hosts for other languages:

* https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-ara/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-bul/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-ces-slk/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-deu/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-fra/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-heb/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-ind/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-ita/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-kor/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-lav/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-lit/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-nld/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-por/list.txt

**Comment by hectorm** [comment]
If you don't want to use the default sources you can specify your own sources in the `/etc/hblock/sources.list` file.

I suggest you check the [hBlock options](https://github.com/hectorm/hblock/blob/master/hblock.1.md) to learn how to use it.
