### ISSUE TITLE
How did you make this file.. hosts_unbound.conf

### ISSUE THREAD

**Issue by bcookatpcsd** [hectorm/hblock#96]
I've just been able to migrate major portions of our internal recursive to unbound.. But I was trying to move some filtering into it rather than pushing upstream.. 

I cannot figure out what the syntax was you used for this file:

https://hblock.molinero.dev/hosts_unbound.conf

Thank you in advance..

**Comment by hectorm** [comment]
That file is automatically generated by [./resources/alt-formats/unbound.conf.sh](https://github.com/hectorm/hblock/blob/HEAD/resources/alt-formats/unbound.conf.sh).

You can also run hBlock with the following options:
```sh
hblock -O ./hosts_unbound.conf -H none -F none -T 'local-zone: "%D" always_nxdomain' -f
```

**Comment by bcookatpcsd** [comment]
Thank you for the response; greatly appreciated. 

I was doing it in a two step.. and not understanding. I thought the template needed the %D AND %R

Thank you for the one liner example.

**Comment by hectorm** [comment]
The template does not actually require any variables. If you check the [./resources/alt-formats/](https://github.com/hectorm/hblock/tree/HEAD/resources/alt-formats) directory you will see more examples.

I hope this has solved your doubts, thank you!
