### ISSUE TITLE
Default Sources: Energized Protection 

### ISSUE THREAD

**Issue by chapters1000** [hectorm/hblock#98]
Edited: /etc/hblock/sources.list

Thank you.

**Comment by hectorm** [comment]
Energized is a consolidation of multiple sources, even among its sources there is hBlock itself. The best thing to do would be to propose the inclusion of specific Energized sources.

My recommendation is that if you want to use Energized you should define it in the sources.list file as you are indicating, but I have no interest in including it by default.
