### ISSUE TITLE
[ERROR] Cannot obtain source

### ISSUE THREAD

**Issue by Elimelech** [hectorm/hblock#99]
If there is an error in the source address of the host file, then the script stops and nothing else happens. Is it possible to make the script work when the host of a file is unavailable?
`root@A9t:/home/luba # hblock --sources /etc/hblock/sources.list --allowlist /etc/hblock/allow.list --denylist /etc/hblock/deny.list
[INFO] Downloading sources
 * https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/adblock-nocoin-list/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/adguard-cname-trackers/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/adguard-simplified/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/dandelionsprout-nordic/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist-rus/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/easyprivacy/list.txt
 * https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt
 * https://raw.githubusercontent.com/MetaMask/eth-phishing-detects/master/src/hosts.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/gfrogeye-firstparty-trackers/list.txt
 * https://raw.githubusercontent.com/hectorm/hmirror/master/data/hostsvn/list.txt
curl: (22) The requested URL returned error: 404
[ERROR] Cannot obtain source: https://raw.githubusercontent.com/MetaMask/eth-phishing-detects/master/src/hosts.txt
root@A9t:/home/luba # /usr/local/bin/hblock: cannot create /tmp/hblock.65431.4f2c1585012d97/2b87f9c0002dce.part: No such file or directory
/usr/local/bin/hblock: cannot create /tmp/hblock.65431.4f2c1585012d97/58aec6780054ee.part: No such file or directory
/usr/local/bin/hblock: cannot create /tmp/hblock.65431.4f2c1585012d97/2b87f9c00040bd.part: No such file or directory
`

**Comment by hectorm** [comment]
I think the `-c` or `--continue` option is what you are looking for.
